#!/usr/bin/env python3
"""Erzeugt alle DOCX-Aktenstuecke fuer die Schaefer-Akte."""
from pathlib import Path
from docx import Document
from docx.shared import Pt, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH

OUT = Path(__file__).resolve().parent.parent / "docx"
OUT.mkdir(exist_ok=True)


def base_doc(title: str):
    doc = Document()
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)
    section = doc.sections[0]
    section.left_margin = Cm(2.5)
    section.right_margin = Cm(2.5)
    section.top_margin = Cm(2.5)
    section.bottom_margin = Cm(2.5)
    return doc


def add_heading(doc, text, level=1):
    h = doc.add_heading(text, level=level)
    for run in h.runs:
        run.font.name = "Calibri"
    return h


def add_para(doc, text, bold=False, align=None, size=None):
    p = doc.add_paragraph()
    if align is not None:
        p.alignment = align
    r = p.add_run(text)
    if bold:
        r.bold = True
    if size:
        r.font.size = Pt(size)
    return p


# 1) AG-Beschluss
def build_ag_beschluss():
    doc = base_doc("AG Nuernberg-Fuerth Beschluss")
    add_para(doc, "Amtsgericht Nuernberg - Familiengericht", bold=True, align=WD_ALIGN_PARAGRAPH.CENTER, size=13)
    add_para(doc, "Az. 110 F 2418/21", align=WD_ALIGN_PARAGRAPH.CENTER)
    add_para(doc, "")
    add_heading(doc, "Beschluss", level=1)
    add_para(doc, "In der Familiensache")
    add_para(doc, "")
    add_para(doc, "Dr. Maximilian Schaefer, Schillerstr. 14, 91054 Erlangen,", bold=True)
    add_para(doc, "- Antragsteller -")
    add_para(doc, "Verfahrensbevollmaechtigter: Rechtsanwalt Andreas Vorndran, Hauptstr. 41, 91054 Erlangen")
    add_para(doc, "")
    add_para(doc, "gegen")
    add_para(doc, "")
    add_para(doc, "Leonie Schaefer geb. Winterstein, Schweinauer Hauptstr. 144, 90441 Nuernberg,", bold=True)
    add_para(doc, "- Antragsgegnerin -")
    add_para(doc, "Verfahrensbevollmaechtigte: Rechtsanwaeltin Helene Soell-Roedelsteiner, Karolinenstr. 27, 90402 Nuernberg")
    add_para(doc, "")
    add_para(doc, "wegen Ehescheidung und Folgesachen")
    add_para(doc, "")
    add_para(doc, "hat das Amtsgericht Nuernberg - Familiengericht - durch die Richterin am Amtsgericht Dr. Barbara Quanten in der nicht oeffentlichen Sitzung vom 28.02.2022, an der mitgewirkt haben die Antragsgegnerin, der Antragsteller und die Verfahrensbevollmaechtigten beider Beteiligten,")
    add_para(doc, "")
    add_para(doc, "am 28. Februar 2022 beschlossen:", bold=True)
    add_para(doc, "")
    add_heading(doc, "Tenor", level=2)
    add_para(doc, "1. Die am 12.09.1987 vor dem Standesbeamten der Stadt Nuernberg, Heiratsregister Nr. 1142/1987, geschlossene Ehe der Beteiligten wird geschieden.")
    add_para(doc, "")
    add_para(doc, "2. Im Wege des Versorgungsausgleichs werden uebertragen:")
    add_para(doc, "2.1 Im Wege der internen Teilung nach § 10 VersAusglG wird zu Lasten des Anrechts des Antragstellers bei der Bayerischen Versorgungskammer - Bayerische Aerzteversorgung - (Mitglieds-Nr. 14-072 184/1958) zugunsten der Antragsgegnerin ein Anrecht in Hoehe von monatlich 2.063,71 EUR, bezogen auf den 30.04.2021 als Ende der Ehezeit, uebertragen; Teilungskosten 500 EUR sind beruecksichtigt.")
    add_para(doc, "2.2 Im Wege der internen Teilung nach § 10 VersAusglG wird zu Lasten des Anrechts des Antragstellers bei der Deutschen Rentenversicherung Nordbayern (Versicherungs-Nr. 65 030258 S 010) zugunsten der Antragsgegnerin ein Anrecht in Hoehe von 1,0917 Entgeltpunkten, bezogen auf den 30.04.2021, uebertragen.")
    add_para(doc, "2.3 Im Wege der externen Teilung nach § 14 VersAusglG wird zu Lasten des Anrechts des Antragstellers bei der Allianz Lebensversicherungs-AG (Vertrags-Nr. 0817 4118 22) ein Kapitalbetrag in Hoehe von 8.736,71 EUR zugunsten einer von der Antragsgegnerin innerhalb von zwei Monaten ab Rechtskraft zu benennenden Zielversorgung uebertragen.")
    add_para(doc, "2.4 Im Wege der externen Teilung nach § 14 VersAusglG wird zu Lasten des Anrechts des Antragstellers bei der Wuerttembergischen Lebensversicherung AG (Vertrags-Nr. 4471 9982 73) ein Kapitalbetrag in Hoehe von 22.165,89 EUR zugunsten einer von der Antragsgegnerin innerhalb von zwei Monaten ab Rechtskraft zu benennenden Zielversorgung uebertragen.")
    add_para(doc, "")
    add_para(doc, "3.1 Im Wege der internen Teilung wird zu Lasten des Anrechts der Antragsgegnerin bei dem Freistaat Bayern (Bayerisches Landesamt fuer Finanzen) zugunsten des Antragstellers ein Anrecht in Hoehe von monatlich 925,00 EUR uebertragen, bezogen auf den 30.04.2021.")
    add_para(doc, "3.2 Im Wege der internen Teilung wird zu Lasten des ehezeitlichen Anrechts der Antragsgegnerin bei der Deutschen Rentenversicherung Bund zugunsten des Antragstellers ein Anrecht in Hoehe von 2,6000 Entgeltpunkten uebertragen, bezogen auf den 30.04.2021.")
    add_para(doc, "")
    add_para(doc, "4. Die Gerichtskosten dieses Verfahrens werden zwischen den Beteiligten geteilt; aussergerichtliche Kosten werden nicht erstattet.")
    add_para(doc, "")
    add_para(doc, "5. Der Verfahrenswert wird auf 26.700 EUR festgesetzt (Scheidung 17.700 EUR; Versorgungsausgleich 9.000 EUR).")
    add_para(doc, "")
    add_heading(doc, "Gruende", level=2)
    add_para(doc, "1. Ehe, Trennung und Scheidungsvoraussetzungen")
    add_para(doc, "Die Beteiligten haben am 12.09.1987 vor dem Standesbeamten der Stadt Nuernberg die Ehe geschlossen. Aus der Ehe sind keine Kinder hervorgegangen. Beide Beteiligten sind deutsche Staatsangehoerige, die ihren gewoehnlichen Aufenthalt im Inland haben.")
    add_para(doc, "Der Antragsteller hat mit Antragsschrift vom 15.05.2021, eingegangen bei Gericht am 18.05.2021, die Scheidung beantragt. Die Antragsschrift wurde der Antragsgegnerin am 19.05.2021 zugestellt. Die Beteiligten leben seit dem 02.04.2021 raeumlich getrennt; eine Versoehnung haben sie ausgeschlossen.")
    add_para(doc, "Die Ehe der Beteiligten ist gescheitert (§ 1565 BGB); das Trennungsjahr ist abgelaufen. Die Ehe ist daher zu scheiden.")
    add_para(doc, "")
    add_para(doc, "2. Versorgungsausgleich und Ehezeit")
    add_para(doc, "Der Versorgungsausgleich ist nach §§ 1, 3 VersAusglG von Amts wegen durchzufuehren. Die Ehezeit nach § 3 Abs. 1 VersAusglG dauerte vom 01.09.1987 bis 30.04.2021.")
    add_para(doc, "Die Versorgungstraeger haben die folgenden ehezeitlichen Anrechte mitgeteilt (Stand der Auskuenfte: zwischen Juli und September 2021):")
    add_para(doc, "")
    add_para(doc, "Antragsteller Dr. Maximilian Schaefer:")
    add_para(doc, "- Bayerische Aerzteversorgung: monatlich 4.127,42 EUR (Ausgleichswert 2.063,71 EUR);")
    add_para(doc, "- DRV Nordbayern: 2,1834 EP (Ausgleichswert 1,0917 EP);")
    add_para(doc, "- Allianz Riester: Deckungskapital 18.473,42 EUR (Ausgleichswert 8.736,71 EUR);")
    add_para(doc, "- Wuerttembergische Direktversicherung: 44.831,77 EUR Deckungskapital (Ausgleichswert 22.165,89 EUR).")
    add_para(doc, "")
    add_para(doc, "Antragsgegnerin Leonie Schaefer:")
    add_para(doc, "- Bayerisches Landesamt fuer Finanzen (Beamtenversorgung Freistaat Bayern): monatlich 1.850 EUR (Ausgleichswert 925 EUR);")
    add_para(doc, "- DRV Bund: 5,2 ehezeitliche Entgeltpunkte bei 12,5 Entgeltpunkten Gesamtkonto (Ausgleichswert 2,6 EP).")
    add_para(doc, "")
    add_para(doc, "3. Antrag auf Ausschluss oder Reduzierung")
    add_para(doc, "Der Antragsteller hat im Termin und in den Schriftsaetzen vom 14.07.2021 und 22.10.2021 den vollstaendigen Ausschluss des Versorgungsausgleichs nach § 27 VersAusglG beantragt. Er hat sich darauf berufen, die Antragsgegnerin sei durch die Erbschaft 2019 (rund 6,9 Mio. EUR) wirtschaftlich lebenslang abgesichert; die Anrechte des Antragstellers seien die einzige Altersversorgung. Hilfsweise hat er die Reduzierung auf die Haelfte beantragt.")
    add_para(doc, "")
    add_para(doc, "Die Antragsgegnerin hat in ihren Schriftsaetzen vom 04.08.2021 und 11.11.2021 sowie im Termin beantragt, den Ausschlussantrag zurueckzuweisen und den VA in voller Hoehe durchzufuehren. Sie hat ausgefuehrt, das Vermoegen sei einseitig erworben, ueberwiegend in Immobilien gebunden und nicht ohne Substanzverluste verwertbar; § 27 sei eine eng auszulegende Ausnahmevorschrift.")
    add_para(doc, "")
    add_para(doc, "4. Keine grobe Unbilligkeit")
    add_para(doc, "Das Gericht folgt der Antragsgegnerin. Nach gefestigter Rechtsprechung (BGH FamRZ 2018, 1746; BGH FamRZ 2014, 1614; BGH FamRZ 2012, 1545) ist § 27 VersAusglG eine eng auszulegende Ausnahmevorschrift. Ein einseitig erworbener und in Immobilien gebundener Vermoegensstamm rechtfertigt fuer sich genommen den Ausschluss des oeffentlich-rechtlichen Halbteilungsgrundsatzes nicht. Die Beteiligten haben in der notariellen Vereinbarung vom 11.11.2021 in § 8 ausdruecklich erklaert, dass die Vereinbarung den Versorgungsausgleich nicht erfasst. Eine grobe Unbilligkeit liegt nicht vor.")
    add_para(doc, "")
    add_para(doc, "Der Versorgungsausgleich wird daher nach Massgabe der unter Ziffer 2 und 3 getroffenen Anordnungen vollstaendig durchgefuehrt.")
    add_para(doc, "")
    add_heading(doc, "Rechtsmittelbelehrung", level=2)
    add_para(doc, "Gegen diesen Beschluss steht den Beteiligten die Beschwerde an das Oberlandesgericht Nuernberg zu. Die Beschwerde ist binnen einer Frist von einem Monat ab Zustellung dieses Beschlusses bei dem Amtsgericht Nuernberg einzulegen.")
    add_para(doc, "")
    add_para(doc, "Nuernberg, den 28. Februar 2022")
    add_para(doc, "")
    add_para(doc, "Dr. Barbara Quanten")
    add_para(doc, "Richterin am Amtsgericht")
    doc.save(OUT / "AG_Nuernberg_Fuerth_Beschluss_28_02_2022.docx")


# 2) OLG-Beschluss
def build_olg_beschluss():
    doc = base_doc("OLG Nuernberg Beschluss")
    add_para(doc, "Oberlandesgericht Nuernberg - 7. Familiensenat", bold=True, align=WD_ALIGN_PARAGRAPH.CENTER, size=13)
    add_para(doc, "Az. 7 UF 743/22", align=WD_ALIGN_PARAGRAPH.CENTER)
    add_para(doc, "")
    add_heading(doc, "Beschluss", level=1)
    add_para(doc, "In der Familiensache")
    add_para(doc, "")
    add_para(doc, "Dr. Maximilian Schaefer, Schillerstr. 14, 91054 Erlangen,", bold=True)
    add_para(doc, "- Antragsteller und Beschwerdefuehrer -")
    add_para(doc, "Verfahrensbevollmaechtigter: Rechtsanwalt Andreas Vorndran, Erlangen")
    add_para(doc, "")
    add_para(doc, "gegen")
    add_para(doc, "")
    add_para(doc, "Leonie Schaefer geb. Winterstein, Schweinauer Hauptstr. 144, 90441 Nuernberg,", bold=True)
    add_para(doc, "- Antragsgegnerin und Beschwerdegegnerin -")
    add_para(doc, "Verfahrensbevollmaechtigte: Rechtsanwaeltin Helene Soell-Roedelsteiner, Nuernberg")
    add_para(doc, "")
    add_para(doc, "wegen Versorgungsausgleichs (Folgesache der Familiensache 110 F 2418/21 AG Nuernberg-Fuerth)")
    add_para(doc, "")
    add_para(doc, "hat der 7. Familiensenat des Oberlandesgerichts Nuernberg durch den Vorsitzenden Richter am Oberlandesgericht Dr. Hans-Werner Pirckheimer, die Richterin am Oberlandesgericht Christina Lampertshausen-Wittmann und den Richter am Oberlandesgericht Dr. Friedhelm Buchberger auf die muendliche Verhandlung vom 18.10.2022")
    add_para(doc, "")
    add_para(doc, "am 14. November 2022 beschlossen:", bold=True)
    add_para(doc, "")
    add_heading(doc, "Tenor", level=2)
    add_para(doc, "1. Auf die Beschwerde des Antragstellers wird der Beschluss des Amtsgerichts Nuernberg - Familiengericht - vom 28.02.2022, Az. 110 F 2418/21, in Ziffer 2 und Ziffer 3 abgeaendert und wie folgt neu gefasst:")
    add_para(doc, "")
    add_para(doc, "  'Ein Versorgungsausgleich findet nach § 27 VersAusglG nicht statt.'")
    add_para(doc, "")
    add_para(doc, "2. Die Gerichtskosten des Beschwerdeverfahrens traegt die Antragsgegnerin; aussergerichtliche Kosten werden nicht erstattet.")
    add_para(doc, "")
    add_para(doc, "3. Der Verfahrenswert fuer das Beschwerdeverfahren wird auf 9.000 EUR festgesetzt.")
    add_para(doc, "")
    add_para(doc, "4. Die Rechtsbeschwerde wird zugelassen.")
    add_para(doc, "")
    add_heading(doc, "Gruende", level=2)
    add_para(doc, "1. Beschwerdegegenstand und unstreitige Anrechte")
    add_para(doc, "Die zulaessige Beschwerde ist begruendet.")
    add_para(doc, "Zwischen den Beteiligten ist allein die Frage streitig, ob der Versorgungsausgleich nach § 27 VersAusglG ganz oder teilweise auszuschliessen ist. Die ehezeitlichen Anrechte sind durch die Auskuenfte der Versorgungstraeger geklaert; gegen die Hoehe der Anrechte werden Einwendungen nicht erhoben.")
    add_para(doc, "")
    add_para(doc, "2. Beweisaufnahme im Beschwerdeverfahren")
    add_para(doc, "Der Senat hat im Termin zur muendlichen Verhandlung vom 18.10.2022 die Beteiligten persoenlich angehoert und ein Sachverstaendigengutachten zur Frage der kurzfristigen Verwertbarkeit der Immobilien der Antragsgegnerin sowie der Belastung der Praxis des Antragstellers im Hinblick auf die Versorgungsanrechte erhoben.")
    add_para(doc, "")
    add_para(doc, "3. Grobe Unbilligkeit nach § 27 VersAusglG")
    add_para(doc, "Der Senat ist der Auffassung, dass im vorliegenden Einzelfall die Durchfuehrung des Versorgungsausgleichs grob unbillig i. S. d. § 27 VersAusglG waere.")
    add_para(doc, "")
    add_para(doc, "3.1 Vermoegenslage der Antragsgegnerin")
    add_para(doc, "Die Antragsgegnerin verfuegt aus der Erbschaft nach ihrem Onkel Theodor Winterstein (verstorben 14.03.2019) ueber ein Reinvermoegen mit einem Verkehrswert von ca. 6,9 Mio. EUR. Davon entfallen rund 4,8 Mio. EUR auf drei vermietete Immobilien (Mehrfamilienhaus Bamberg, Gewerbeimmobilie Forchheim, ETW Muenchen), 1,2 Mio. EUR auf ein gut diversifiziertes Wertpapierdepot und 450.000 EUR auf Festgelder. Die Mieteinnahmen betragen monatlich zusammen ca. 23.300 EUR brutto.")
    add_para(doc, "Damit ist die Antragsgegnerin ueber jeden Zweifel hinaus lebenslang wirtschaftlich abgesichert. Hinzu treten ihre eigene Beamtenversorgung (1.850 EUR monatlich) sowie ihre DRV-Anwartschaft.")
    add_para(doc, "")
    add_para(doc, "3.2 Vermoegenslage des Antragstellers")
    add_para(doc, "Der Antragsteller verfuegt ueber ein Reinvermoegen von rund 195.000 EUR und kein nennenswertes Liquidationskapital. Die Praxisertraege gehen aufgrund seines Alters (Jg. 1958) und einer 2020 diagnostizierten Verschleisserkrankung des Bewegungsapparats kontinuierlich zurueck; die Praxisabgabe ist innerhalb der naechsten 5-7 Jahre vorgesehen. Die Anrechte bei der Bayerischen Aerzteversorgung sind die zentrale Saeule seiner Altersversorgung.")
    add_para(doc, "Bei vollstaendiger Durchfuehrung des Versorgungsausgleichs wuerde sich die Bruttorente des Antragstellers von 4.127,42 EUR auf 2.063,71 EUR halbieren, was unter Beruecksichtigung der laufenden Lebenshaltungskosten in Erlangen seine Existenzgrundlage erheblich gefaehrden wuerde.")
    add_para(doc, "")
    add_para(doc, "3.3 Wertung im Lichte der Rechtsprechung")
    add_para(doc, "Zwar ist § 27 VersAusglG nach gefestigter Rechtsprechung des Bundesgerichtshofs (BGH FamRZ 2018, 1746; BGH FamRZ 2014, 1614; BGH FamRZ 2012, 1545) eng auszulegen und nur in Ausnahmefaellen einschlaegig. Eine solche Ausnahmekonstellation liegt jedoch hier vor: Die ausgleichsberechtigte Person ist durch einseitig erworbenes Vermoegen lebenslang abgesichert, waehrend die ausgleichspflichtige Person bei vollstaendiger Durchfuehrung in ihrer Altersversorgung erheblich beeintraechtigt wuerde. Der von der Antragsgegnerin angefuehrte Einwand, die Verwertbarkeit der Immobilien sei eingeschraenkt, ueberzeugt nicht: Bereits die laufenden Mieteinnahmen uebersteigen den Bedarf der Antragsgegnerin um ein Mehrfaches; eine teilweise Beleihung oder Verwertung waere ohne weiteres moeglich.")
    add_para(doc, "Hinzu kommt, dass die Beteiligten ueber Jahrzehnte eine gemeinsame Vermoegensplanung verfolgt haben, wonach die Versorgungsanrechte des Antragstellers nach der Pensionierung Ihrer gemeinsamen Lebensfuehrung dienen sollten; mit der Erbschaft 2019 ist die Antragsgegnerin von dieser Planung wirtschaftlich vollstaendig unabhaengig geworden.")
    add_para(doc, "")
    add_para(doc, "3.4 § 8 der notariellen Vereinbarung 11.11.2021")
    add_para(doc, "Die Vereinbarung der Beteiligten vom 11.11.2021 (UR-Nr. 1442/2021 Notar Dr. Wamsdoerfer) hat den Versorgungsausgleich ausdruecklich offen gehalten (§ 8). Eine Erstreckung der Vereinbarung auf den VA scheidet daher aus; das Gericht entscheidet von Amts wegen.")
    add_para(doc, "")
    add_para(doc, "3.5 Rechtsfolge")
    add_para(doc, "Bei Abwaegung aller Umstaende des Einzelfalls ist der Versorgungsausgleich nach § 27 VersAusglG vollstaendig auszuschliessen. Eine bloss teilweise Reduzierung des Ausgleichs wuerde dem Befund nicht gerecht, weil die wirtschaftliche Absicherung der Antragsgegnerin auch eine teilweise Schmaelerung der Anrechte des Antragstellers entbehrlich macht.")
    add_para(doc, "")
    add_para(doc, "4. Kosten und Verfahrenswert")
    add_para(doc, "Die Kostenentscheidung folgt aus § 150 FamFG. Die Festsetzung des Verfahrenswertes beruht auf § 50 FamGKG.")
    add_para(doc, "")
    add_para(doc, "5. Zulassung der Rechtsbeschwerde")
    add_para(doc, "Die Rechtsbeschwerde wird zugelassen, weil die Rechtssache grundsaetzliche Bedeutung hat (§ 70 Abs. 2 Nr. 1 FamFG). Die Frage, ob und unter welchen Voraussetzungen einseitig durch Erbschaft erworbenes Immobilienvermoegen der ausgleichsberechtigten Person zum vollstaendigen Ausschluss des Versorgungsausgleichs fuehrt, ist hoechstrichterlich nicht eindeutig geklaert.")
    add_para(doc, "")
    add_heading(doc, "Rechtsmittelbelehrung", level=2)
    add_para(doc, "Gegen diesen Beschluss kann Rechtsbeschwerde zum Bundesgerichtshof eingelegt werden. Die Rechtsbeschwerde ist binnen einer Frist von einem Monat ab Zustellung dieses Beschlusses durch einen beim Bundesgerichtshof zugelassenen Rechtsanwalt einzulegen. Die Begruendungsfrist betraegt zwei Monate ab Zustellung.")
    add_para(doc, "")
    add_para(doc, "Nuernberg, den 14. November 2022")
    add_para(doc, "")
    add_para(doc, "Dr. Pirckheimer  -  Lampertshausen-Wittmann  -  Dr. Buchberger")
    doc.save(OUT / "OLG_Nuernberg_Beschluss_14_11_2022.docx")


def build_beschwerdebegruendung_vorndran():
    doc = base_doc("Beschwerdebegruendung Vorndran")
    add_para(doc, "Vorndran und Brennstetter Rechtsanwaelte mbB", bold=True, align=WD_ALIGN_PARAGRAPH.CENTER)
    add_para(doc, "Hauptstr. 41, 91054 Erlangen", align=WD_ALIGN_PARAGRAPH.CENTER)
    add_para(doc, "")
    add_para(doc, "Oberlandesgericht Nuernberg", bold=True)
    add_para(doc, "7. Familiensenat")
    add_para(doc, "Fuerther Str. 110")
    add_para(doc, "90429 Nuernberg")
    add_para(doc, "")
    add_para(doc, "Erlangen, 22.05.2022")
    add_para(doc, "")
    add_para(doc, "Az. 7 UF 743/22 (AG Nuernberg-Fuerth 110 F 2418/21)", bold=True)
    add_para(doc, "In der Familiensache Dr. Maximilian Schaefer ./. Leonie Schaefer")
    add_para(doc, "")
    add_heading(doc, "Beschwerdebegruendung", level=1)
    add_para(doc, "In der vorbezeichneten Familiensache wird namens und im Auftrag des Antragstellers und Beschwerdefuehrers Beschwerdebegruendung wie folgt eingelegt.")
    add_para(doc, "")
    add_heading(doc, "1. Antraege", level=2)
    add_para(doc, "Wir beantragen,")
    add_para(doc, "1. den Beschluss des Amtsgerichts Nuernberg - Familiengericht - vom 28.02.2022, Az. 110 F 2418/21, in den Ziffern 2 und 3 abzuaendern;")
    add_para(doc, "2. den Versorgungsausgleich nach § 27 VersAusglG vollstaendig auszuschliessen;")
    add_para(doc, "3. hilfsweise: den Versorgungsausgleich auf die Haelfte zu reduzieren;")
    add_para(doc, "4. die Kosten des Verfahrens der Antragsgegnerin aufzuerlegen.")
    add_para(doc, "")
    add_heading(doc, "2. Sachverhalt", level=2)
    add_para(doc, "2.1 Vermoegensverhaeltnisse der Antragsgegnerin")
    add_para(doc, "Die Antragsgegnerin verfuegt seit der Erbschaft nach ihrem Onkel Theodor Winterstein 14.03.2019 ueber Reinvermoegen von ca. 6,9 Mio. EUR. Die Mieteinnahmen aus den geerbten drei Immobilien betragen brutto 23.300 EUR monatlich. Zusammen mit den Dividenden aus dem Wertpapierdepot ergibt sich ein laufender Brutto-Einkommensstrom von ueber 28.000 EUR monatlich.")
    add_para(doc, "Beweis: Vorlage des Erbschaftsteuerbescheids des Finanzamts Bamberg vom 05.03.2020, Steuernummer 207/281/40918; Vorlage der Mietzahlungsuebersicht der Hausverwaltung Pirsch und Maerz GmbH Bamberg; Vorlage der Depotauszuege der DZ Privatbank Stand 31.12.2021.")
    add_para(doc, "")
    add_para(doc, "2.2 Vermoegensverhaeltnisse des Antragstellers")
    add_para(doc, "Der Antragsteller verfuegt ueber Reinvermoegen von rund 195.000 EUR. Seine Praxis hat 2021 einen Jahresgewinn von 211.000 EUR vor Steuern ausgewiesen, mit fallender Tendenz. Im Februar 2020 ist beim Antragsteller eine schwere Coxarthrose diagnostiziert worden, die eine Praxisaufgabe in den naechsten 5-7 Jahren erfordert.")
    add_para(doc, "Beweis: Bilanz Praxis 2018-2021 (Steuerberater Berthold Faulhammer); ICD-10 Diagnose M16.0 Coxarthrose Universitaetsklinik Erlangen Orthopaedie Dr. Stadlhuber 18.02.2020; Sachverstaendigengutachten Praxiswert.")
    add_para(doc, "")
    add_para(doc, "2.3 Gemeinsame Vermoegensplanung")
    add_para(doc, "Die Beteiligten haben ueber Jahrzehnte eine gemeinsame Lebensplanung verfolgt: Der Antragsteller hat in der ersten Ehehaelfte (1987-2003) den groessten Teil der Familienlast getragen; die Antragsgegnerin hat den Aufbau der Praxis durch Steuererklaerungen, Praxis-Buchfuehrung und Akquise persoenlich unterstuetzt.")
    add_para(doc, "Beweis: Aussage der Antragsgegnerin; Vernehmung von Steuerberater Faulhammer; Vorlage der Praxis-Buchfuehrungsunterlagen 1992-2004.")
    add_para(doc, "")
    add_heading(doc, "3. Rechtliche Wuerdigung", level=2)
    add_para(doc, "Es liegt grobe Unbilligkeit i. S. d. § 27 VersAusglG vor. § 27 VersAusglG ist nach gefestigter Rechtsprechung des BGH (BGH FamRZ 2018, 1746; BGH FamRZ 2014, 1614; BGH FamRZ 2012, 1545) zwar eng auszulegen, aber gerade in Vermoegenskonstellationen einschlaegig, in denen die ausgleichsberechtigte Person bereits lebenslang abgesichert ist und die ausgleichspflichtige Person bei vollstaendiger Durchfuehrung in ihrer Altersversorgung erheblich beeintraechtigt wuerde.")
    add_para(doc, "")
    add_para(doc, "Dies ist hier der Fall:")
    add_para(doc, "1. Die Antragsgegnerin ist durch das ererbte Vermoegen wirtschaftlich vollstaendig abgesichert.")
    add_para(doc, "2. Der Antragsteller ist auf seine Anrechte bei der Bayerischen Aerzteversorgung als Hauptsaeule seiner Alterssicherung angewiesen.")
    add_para(doc, "3. Die Halbierung der Bayerischen-Aerzteversorgung-Rente von 4.127 EUR auf rund 2.063 EUR wuerde die Existenzgrundlage des Antragstellers in der Praxis-Abschlussphase und in der Rentenphase erheblich gefaehrden.")
    add_para(doc, "4. § 8 der notariellen Vereinbarung 11.11.2021 hindert die Anwendung des § 27 nicht. Selbst wenn man annehmen wollte, dass der dort vereinbarte pauschale Zugewinnausgleich (385.000 EUR) bereits eine Beruecksichtigung der Vermoegensverhaeltnisse darstellt, schliesst dies eine zusaetzliche Korrektur ueber § 27 VersAusglG nicht aus.")
    add_para(doc, "")
    add_para(doc, "Mit kollegialen Gruessen")
    add_para(doc, "")
    add_para(doc, "Andreas Vorndran")
    add_para(doc, "Rechtsanwalt, Fachanwalt fuer Familienrecht")
    doc.save(OUT / "Beschwerdebegruendung_Vorndran_22_05_2022.docx")


def build_beschwerdeerwiderung_soell():
    doc = base_doc("Beschwerdeerwiderung Soell")
    add_para(doc, "Soell Roedelsteiner und Partner mbB", bold=True, align=WD_ALIGN_PARAGRAPH.CENTER)
    add_para(doc, "Karolinenstr. 27, 90402 Nuernberg", align=WD_ALIGN_PARAGRAPH.CENTER)
    add_para(doc, "")
    add_para(doc, "Oberlandesgericht Nuernberg")
    add_para(doc, "7. Familiensenat")
    add_para(doc, "Fuerther Str. 110, 90429 Nuernberg")
    add_para(doc, "")
    add_para(doc, "Nuernberg, 04.07.2022")
    add_para(doc, "")
    add_para(doc, "Az. 7 UF 743/22", bold=True)
    add_para(doc, "In der Familiensache Schaefer ./. Schaefer")
    add_para(doc, "")
    add_heading(doc, "Beschwerdeerwiderung", level=1)
    add_para(doc, "Namens und mit Vollmacht der Antragsgegnerin und Beschwerdegegnerin Frau Leonie Schaefer beantragen wir,")
    add_para(doc, "")
    add_para(doc, "die Beschwerde des Antragstellers gegen den Beschluss des AG Nuernberg-Fuerth vom 28.02.2022 zurueckzuweisen.", bold=True)
    add_para(doc, "")
    add_heading(doc, "Begruendung", level=2)
    add_para(doc, "1. Verteidigungsgrund: Strenge Ausnahmenatur des § 27 VersAusglG")
    add_para(doc, "§ 27 VersAusglG ist nach gefestigter Rechtsprechung des Bundesgerichtshofs eine eng auszulegende Ausnahmevorschrift. Der Senat darf nur in extremen Konstellationen den verfassungsrechtlich abgesicherten Halbteilungsgrundsatz (Art. 6 GG; BVerfG 53, 257) durchbrechen. Der Antragsteller hat keine solche Konstellation dargetan.")
    add_para(doc, "Zitiert seien zunaechst die einschlaegigen Leitentscheidungen:")
    add_para(doc, "- BGH, Beschluss vom 27.06.2018 - XII ZB 73/17 = FamRZ 2018, 1746;")
    add_para(doc, "- BGH, Beschluss vom 17.09.2014 - XII ZB 156/14 = FamRZ 2014, 1614;")
    add_para(doc, "- BGH, Beschluss vom 11.07.2012 - XII ZB 459/11 = FamRZ 2012, 1545.")
    add_para(doc, "")
    add_para(doc, "2. Privilegierung der Erbschaft nach § 1374 Abs. 2 BGB")
    add_para(doc, "Das Vermoegen der Antragsgegnerin stammt im Wesentlichen aus einer einseitigen Erbschaft des Onkels Theodor Winterstein (verstorben 14.03.2019, Erbschein AG Bamberg VI 1138/19 vom 02.09.2019). Solches Vermoegen ist nach § 1374 Abs. 2 BGB im Zugewinnausgleich privilegiert. Diese gesetzgeberische Privilegierung darf nicht ueber den Versorgungsausgleich umgangen werden.")
    add_para(doc, "")
    add_para(doc, "3. Substanzgebundenheit und eingeschraenkte Verwertbarkeit")
    add_para(doc, "Der Antragsteller stellt das ererbte Vermoegen so dar, als sei es jederzeit liquide. Dies ist unzutreffend. Von den 6,9 Mio. EUR Verkehrswert entfallen 4,8 Mio. EUR auf drei Immobilien (Mehrfamilienhaus Bamberg, Gewerbeimmobilie Forchheim, ETW Muenchen), die kurzfristig nicht ohne erhebliche Substanzverluste verwertbar sind; Mieter sind langfristig gebunden. 1,2 Mio. EUR liegen in einem konservativ ausgerichteten Wertpapierdepot, das ueberwiegend Stiftungs- und Pensionsfondscharakter hat. Lediglich 450.000 EUR Festgelder sind kurzfristig liquide.")
    add_para(doc, "Eine Beleihung der Immobilien zur Bedienung eines fiktiven Versorgungsausfalls ist altersbedingt (Antragsgegnerin Jg. 1961) und marktbedingt eingeschraenkt; die Sparkasse Bamberg hat mit Schreiben vom 14.02.2022 mitgeteilt, dass eine Vollvalutierung nur bis 60 Prozent des Verkehrswerts und nur fuer maximal 10 Jahre erfolgt.")
    add_para(doc, "")
    add_para(doc, "4. Keine gemeinsame Vermoegensplanung")
    add_para(doc, "Der Vortrag des Antragstellers zur 'gemeinsamen Vermoegensplanung' ist unsubstantiiert und wird hilfsweise mit Nichtwissen bestritten. Die Praxis stand bereits bei Eheschliessung 1987; die Antragsgegnerin hat lediglich eine zeitweise Buchfuehrung uebernommen, die in den Praxiskostenstellen abgegolten war.")
    add_para(doc, "")
    add_para(doc, "5. § 8 der notariellen Vereinbarung 11.11.2021")
    add_para(doc, "Die Beteiligten haben in § 8 der Notariellen Vereinbarung ausdruecklich vereinbart, dass der oeffentlich-rechtliche Versorgungsausgleich von der Vereinbarung nicht erfasst wird. Diese ausdruekliche Aussparung schliesst eine Beruecksichtigung der Vermoegensverhaeltnisse, die durch die Notarvereinbarung pauschal ausgeglichen wurden (385.000 EUR), im VA aus. Eine inhaltliche Erstreckung der Vereinbarung kommt nicht in Betracht.")
    add_para(doc, "")
    add_para(doc, "6. Anwartschaften des Antragstellers ausreichend")
    add_para(doc, "Auch nach vollstaendiger Durchfuehrung des VA verbleiben dem Antragsteller eine Bayerische-Aerzteversorgungs-Rente von rund 2.063 EUR monatlich, eine geringe DRV-Rente sowie Praxisertraege und ein Praxis-Verkaufserloes von voraussichtlich 350.000 bis 450.000 EUR. Die Existenzgrundlage des Antragstellers ist damit nicht gefaehrdet.")
    add_para(doc, "")
    add_para(doc, "7. Zusammenfassung")
    add_para(doc, "Eine grobe Unbilligkeit i. S. d. § 27 VersAusglG liegt nicht vor. Der Halbteilungsgrundsatz ist zu wahren. Die Beschwerde ist zurueckzuweisen.")
    add_para(doc, "")
    add_para(doc, "Mit freundlichen kollegialen Gruessen")
    add_para(doc, "")
    add_para(doc, "Helene Soell-Roedelsteiner")
    add_para(doc, "Rechtsanwaeltin, Fachanwaeltin fuer Familienrecht")
    doc.save(OUT / "Beschwerdeerwiderung_Soell_04_07_2022.docx")


def build_notarvereinbarung():
    doc = base_doc("Notarielle Vereinbarung 11.11.2021")
    add_para(doc, "Urkundenrolle Nr. 1442 / 2021", bold=True, align=WD_ALIGN_PARAGRAPH.CENTER)
    add_para(doc, "")
    add_para(doc, "Verhandelt zu Nuernberg am elften November des Jahres zweitausendeinundzwanzig (11.11.2021)", align=WD_ALIGN_PARAGRAPH.CENTER)
    add_para(doc, "")
    add_para(doc, "Vor mir, dem unterzeichnenden Notar")
    add_para(doc, "")
    add_para(doc, "Dr. Holger Wamsdoerfer", bold=True)
    add_para(doc, "Notariat Pirckheimerstr. 12, 90408 Nuernberg")
    add_para(doc, "")
    add_para(doc, "erschienen heute:")
    add_para(doc, "")
    add_para(doc, "1. Herr Dr. Maximilian Schaefer, Zahnarzt, geboren am 03.02.1958, wohnhaft Schillerstr. 14, 91054 Erlangen, ausgewiesen durch Bundespersonalausweis-Nr. T7Y8R2M4J9, gueltig bis 22.04.2026 - im Folgenden 'der Ehemann' -")
    add_para(doc, "")
    add_para(doc, "2. Frau Leonie Schaefer geb. Winterstein, Grundschullehrerin, geboren am 11.06.1961, wohnhaft Schweinauer Hauptstr. 144, 90441 Nuernberg, ausgewiesen durch Bundespersonalausweis-Nr. L3K4M8N1Q7, gueltig bis 11.03.2027 - im Folgenden 'die Ehefrau' -")
    add_para(doc, "")
    add_para(doc, "Die Erschienenen erklaerten zur notariellen Niederschrift:")
    add_para(doc, "")
    add_heading(doc, "§ 1 Vorbemerkungen", level=2)
    add_para(doc, "(1) Wir haben am 12.09.1987 in Nuernberg die Ehe geschlossen. Wir leben in dem gesetzlichen Gueterstand der Zugewinngemeinschaft. Kinder sind aus der Ehe nicht hervorgegangen.")
    add_para(doc, "(2) Wir leben raeumlich seit dem 02.04.2021 getrennt. Vor dem Amtsgericht Nuernberg-Fuerth - Familiengericht - ist unter dem Aktenzeichen 110 F 2418/21 das Scheidungsverfahren anhaengig. Die Beteiligten beabsichtigen, die nachstehende Vereinbarung zur Erledigung der vermoegensrechtlichen Folgen der Scheidung zu schliessen.")
    add_para(doc, "")
    add_heading(doc, "§ 2 Zugewinnausgleich - Pauschalbetrag", level=2)
    add_para(doc, "Zur Abgeltung saemtlicher Zugewinnausgleichsanspruechen der Ehefrau gegen den Ehemann und umgekehrt verpflichtet sich die Ehefrau, an den Ehemann einen Betrag in Hoehe von")
    add_para(doc, "")
    add_para(doc, "385.000,00 EUR (in Worten: dreihundertfuenfundachtzigtausend Euro)", bold=True, align=WD_ALIGN_PARAGRAPH.CENTER)
    add_para(doc, "")
    add_para(doc, "zu zahlen. Die Zahlung erfolgt binnen 14 Tagen nach Rechtskraft des Scheidungsbeschlusses auf das vom Ehemann zu benennende Konto. Mit dieser Zahlung sind saemtliche Zugewinnausgleichsanspruechen der Beteiligten gegeneinander erledigt; die Beteiligten verzichten wechselseitig auf weitergehende Anspruechen.")
    add_para(doc, "")
    add_heading(doc, "§ 3 Hausrat", level=2)
    add_para(doc, "Die Beteiligten haben den Hausrat einvernehmlich aufgeteilt. Streit ueber Hausrat besteht nicht.")
    add_para(doc, "")
    add_heading(doc, "§ 4 Ehewohnung", level=2)
    add_para(doc, "Der Ehemann ist am 02.04.2021 aus der bisherigen Ehewohnung Schweinauer Hauptstr. 144, 90441 Nuernberg, ausgezogen. Die Ehewohnung verbleibt der Ehefrau zur alleinigen Nutzung. Die Beteiligten verzichten wechselseitig auf weitere Anspruechen die Ehewohnung betreffend.")
    add_para(doc, "")
    add_heading(doc, "§ 5 Unterhalt", level=2)
    add_para(doc, "Die Beteiligten verzichten gegenseitig auf nachehelichen Unterhalt fuer den Fall ihrer Scheidung sowie fuer den Fall der Wiederheirat und fuer die Zeit der Trennung. Sie kennen die rechtliche Tragweite dieses Verzichts; der Notar hat sie auf die Bedeutung des § 1585c BGB hingewiesen.")
    add_para(doc, "")
    add_heading(doc, "§ 6 Lebensversicherung als Versorgungsausgleich-Sicherheit", level=2)
    add_para(doc, "Die Beteiligten erklaeren, dass die Lebensversicherung der Allianz Versicherung Nr. 0817 4118 22 und die Direktversicherung Wuerttembergische Nr. 4471 9982 73 nicht Gegenstand dieser Vereinbarung sind; sie sind ausschliesslich Gegenstand des Versorgungsausgleichs.")
    add_para(doc, "")
    add_heading(doc, "§ 7 Erbschaft Winterstein", level=2)
    add_para(doc, "Die Beteiligten stellen klar, dass die Erbschaft der Ehefrau nach ihrem Onkel Theodor Winterstein (verstorben 14.03.2019) ein nach § 1374 Abs. 2 BGB privilegiertes Vermoegen darstellt. Die Beteiligten haben diese Privilegierung bei der Berechnung des Pauschalbetrags des § 2 angemessen beruecksichtigt; sie verzichten auf eine weitergehende Aufschluesselung.")
    add_para(doc, "")
    add_heading(doc, "§ 8 Versorgungsausgleich - ausdruecklich ausgenommen", level=2)
    add_para(doc, "(1) Die vorliegende Vereinbarung erstreckt sich ausdruecklich nicht auf den oeffentlich-rechtlichen Versorgungsausgleich. Die Beteiligten erklaeren, dass der Versorgungsausgleich allein durch das Familiengericht von Amts wegen entschieden wird.")
    add_para(doc, "(2) Die Beteiligten sind durch den Notar darueber aufgeklaert worden, dass eine Vereinbarung ueber den Ausschluss oder die Modifizierung des Versorgungsausgleichs nach § 8 VersAusglG i. V. m. § 1408 BGB der notariellen Form bedarf und im Einzelfall der Inhalts- und Wirksamkeitskontrolle durch das Familiengericht unterliegt. Die Beteiligten haben sich entschieden, eine solche Vereinbarung nicht zu treffen.")
    add_para(doc, "")
    add_heading(doc, "§ 9 Belehrungen und Schlussbestimmungen", level=2)
    add_para(doc, "Der Notar hat die Beteiligten ueber die Tragweite saemtlicher Erklaerungen, insbesondere ueber die Bedeutung des Verzichts auf nachehelichen Unterhalt und ueber den Inhalt des § 1374 Abs. 2 BGB, eingehend belehrt. Die Beteiligten haben erklaert, dass sie die Vereinbarung in voller Kenntnis ihrer Tragweite schliessen.")
    add_para(doc, "")
    add_para(doc, "Vorgelesen, genehmigt und unterschrieben:")
    add_para(doc, "")
    add_para(doc, "Dr. Maximilian Schaefer      Leonie Schaefer geb. Winterstein")
    add_para(doc, "")
    add_para(doc, "Dr. Holger Wamsdoerfer, Notar")
    doc.save(OUT / "Notarielle_Vereinbarung_11_11_2021.docx")


def build_vollmacht_bgh():
    doc = base_doc("Vollmacht Ehrlinger")
    add_para(doc, "VOLLMACHT", bold=True, align=WD_ALIGN_PARAGRAPH.CENTER, size=16)
    add_para(doc, "")
    add_para(doc, "Untervollmacht zur Vertretung vor dem Bundesgerichtshof", align=WD_ALIGN_PARAGRAPH.CENTER)
    add_para(doc, "")
    add_para(doc, "")
    add_para(doc, "Die unterzeichnete Vollmachtgeberin")
    add_para(doc, "")
    add_para(doc, "Frau Leonie Schaefer geb. Winterstein", bold=True)
    add_para(doc, "geboren am 11.06.1961 in Nuernberg")
    add_para(doc, "wohnhaft Schweinauer Hauptstr. 144, 90441 Nuernberg")
    add_para(doc, "")
    add_para(doc, "erteilt hiermit")
    add_para(doc, "")
    add_para(doc, "Frau Rechtsanwaeltin Dr. Susanne Ehrlinger", bold=True)
    add_para(doc, "und der Sozietaet")
    add_para(doc, "Dr. Ehrlinger und Partner Rechtsanwaelte beim Bundesgerichtshof", bold=True)
    add_para(doc, "Reinhold-Frank-Str. 24, 76133 Karlsruhe")
    add_para(doc, "")
    add_para(doc, "die unwiderrufliche Untervollmacht zur Vertretung vor dem Bundesgerichtshof in der Sache:")
    add_para(doc, "")
    add_para(doc, "OLG Nuernberg Az. 7 UF 743/22", bold=True)
    add_para(doc, "Rechtsbeschwerde gegen den Beschluss vom 14.11.2022", bold=True)
    add_para(doc, "")
    add_para(doc, "Die Vollmacht umfasst insbesondere die Befugnis:")
    add_para(doc, "1. Rechtsbeschwerde gegen den Beschluss des OLG Nuernberg vom 14.11.2022 einzulegen und zu begruenden;")
    add_para(doc, "2. Antraege zu stellen und Erklaerungen abzugeben, soweit dies fuer die Vertretung erforderlich ist;")
    add_para(doc, "3. Termine wahrzunehmen, schriftsaetzliche und muendliche Verhandlungen zu fuehren;")
    add_para(doc, "4. Vergleiche und sonstige verfahrensbeendende Erklaerungen abzugeben;")
    add_para(doc, "5. Untervollmacht zu erteilen, soweit dies geboten erscheint.")
    add_para(doc, "")
    add_para(doc, "Die Hauptvollmacht der Frau Rechtsanwaeltin Helene Soell-Roedelsteiner, Karolinenstr. 27, 90402 Nuernberg, vom 22.05.2021 wird damit erweitert.")
    add_para(doc, "")
    add_para(doc, "Nuernberg, den 25.11.2022")
    add_para(doc, "")
    add_para(doc, "____________________________________")
    add_para(doc, "Leonie Schaefer geb. Winterstein")
    doc.save(OUT / "Vollmacht_BGH_Ehrlinger_25_11_2022.docx")


def build_sitzungsprotokoll_olg():
    doc = base_doc("Sitzungsprotokoll OLG 18.10.2022")
    add_para(doc, "OBERLANDESGERICHT NUERNBERG", bold=True, align=WD_ALIGN_PARAGRAPH.CENTER, size=13)
    add_para(doc, "7. Familiensenat", align=WD_ALIGN_PARAGRAPH.CENTER)
    add_para(doc, "")
    add_para(doc, "Az. 7 UF 743/22", bold=True, align=WD_ALIGN_PARAGRAPH.CENTER)
    add_para(doc, "")
    add_heading(doc, "Protokoll", level=1)
    add_para(doc, "ueber die oeffentliche Sitzung")
    add_para(doc, "")
    add_para(doc, "vom 18. Oktober 2022", bold=True)
    add_para(doc, "10:00 Uhr bis 12:35 Uhr")
    add_para(doc, "Sitzungssaal 224, Justizzentrum Nuernberg, Fuerther Str. 110")
    add_para(doc, "")
    add_para(doc, "Anwesend:")
    add_para(doc, "Vorsitzender Richter am Oberlandesgericht Dr. Hans-Werner Pirckheimer")
    add_para(doc, "Richterin am Oberlandesgericht Christina Lampertshausen-Wittmann")
    add_para(doc, "Richter am Oberlandesgericht Dr. Friedhelm Buchberger")
    add_para(doc, "Urkundsbeamter der Geschaeftsstelle: Justizinspektor Manuel Brueckl")
    add_para(doc, "")
    add_para(doc, "In der Familiensache")
    add_para(doc, "")
    add_para(doc, "Dr. Maximilian Schaefer ./. Leonie Schaefer", bold=True)
    add_para(doc, "")
    add_para(doc, "erscheinen:")
    add_para(doc, "1. Antragsteller und Beschwerdefuehrer: Dr. Maximilian Schaefer, persoenlich,")
    add_para(doc, "   begleitet von Rechtsanwalt Andreas Vorndran;")
    add_para(doc, "2. Antragsgegnerin und Beschwerdegegnerin: Leonie Schaefer geb. Winterstein, persoenlich,")
    add_para(doc, "   begleitet von Rechtsanwaeltin Helene Soell-Roedelsteiner.")
    add_para(doc, "")
    add_para(doc, "Der Vorsitzende eroeffnet die Sitzung und stellt fest, dass die Sache zur Verhandlung steht.")
    add_para(doc, "")
    add_para(doc, "Der Sachverhalt wird durch die Berichterstatterin Lampertshausen-Wittmann zusammengefasst.")
    add_para(doc, "")
    add_heading(doc, "1. Anhoerung des Antragstellers", level=2)
    add_para(doc, "Dr. Schaefer wird zu seinen wirtschaftlichen Verhaeltnissen befragt. Er gibt an, seine Praxis erziele aktuell rund 211.000 EUR Gewinn pro Jahr; die Tendenz sei aufgrund einer 2020 diagnostizierten Coxarthrose fallend. Eine Praxisabgabe in fuenf bis sieben Jahren sei vorgesehen. Sein Vermoegen betrage rund 195.000 EUR; nennenswerte Ersparnisse seien nicht vorhanden. Die Anrechte bei der Bayerischen Aerzteversorgung in Hoehe von 4.127,42 EUR seien seine zentrale Altersvorsorge.")
    add_para(doc, "")
    add_heading(doc, "2. Anhoerung der Antragsgegnerin", level=2)
    add_para(doc, "Frau Schaefer wird zu ihrem Erbe Winterstein 2019 und zu ihren Vermoegensverhaeltnissen befragt. Sie schildert, dass das Erbe einseitig erworben und ueberwiegend in Immobilien gebunden sei. Die Mieteinnahmen verwende sie zu rund 60 Prozent fuer laufende Instandhaltung, Verwaltung und Steuern; die verbleibenden 40 Prozent fliessen in ein Ruecklagenkonto fuer Modernisierungen.")
    add_para(doc, "Sie weist darauf hin, dass sie ihrerseits eine Beamtenversorgung von 1.850 EUR und ein DRV-Gesamtkonto von 12,5 Entgeltpunkten habe, aus dem nur 5,2 Entgeltpunkte in die Ehezeit fielen; sie sei nicht auf den Versorgungsausgleich angewiesen, betone aber, dass dies fuer den Halbteilungsgrundsatz irrelevant sei.")
    add_para(doc, "")
    add_heading(doc, "3. Beweisaufnahme - Sachverstaendiger", level=2)
    add_para(doc, "Auf Beschluss des Senats vom 12.09.2022 erstattet der Wirtschaftspruefer und Sachverstaendige Dipl.-Kfm. Helmut Weisbacher (Sachverstaendigenbuero Weisbacher und Partner, Erlangen) muendlich sein Gutachten zur Verkehrswert- und Verwertbarkeitslage der drei Immobilien der Antragsgegnerin sowie zum Praxiswert des Antragstellers.")
    add_para(doc, "")
    add_para(doc, "Der Sachverstaendige fuehrt aus:")
    add_para(doc, "- Verkehrswerte (Stichtag 31.12.2021): Mehrfamilienhaus Bamberg 2.795.000 EUR; Gewerbeimmobilie Forchheim 1.510.000 EUR; ETW Muenchen 945.000 EUR; insgesamt 5.250.000 EUR.")
    add_para(doc, "- Verwertbarkeit: Mehrfamilienhaus Bamberg kurzfristig verwertbar mit Abschlag von 8-12 Prozent; Gewerbeimmobilie Forchheim aufgrund der Spezialnutzung mit Abschlag von 15-20 Prozent; ETW Muenchen kurzfristig verwertbar mit Abschlag von 5-8 Prozent.")
    add_para(doc, "- Beleihung: Bei der Sparkasse Bamberg ist eine Vollvalutierung bis 60 Prozent des Verkehrswerts moeglich; absolute Beleihbarkeit ca. 3,15 Mio. EUR.")
    add_para(doc, "- Praxis Dr. Schaefer: Ertragswertverfahren ergibt Praxiswert von 380.000 bis 470.000 EUR (Bandbreite je nach Praxisuebergabe-Zeitpunkt).")
    add_para(doc, "")
    add_heading(doc, "4. Vergleichsverhandlungen", level=2)
    add_para(doc, "Der Vorsitzende regt einen Vergleich an: Reduzierung des VA auf 60 Prozent gegen Verzicht der Antragsgegnerin auf etwaige Pflichtteilsanspruechen aus einem spaeteren Erbgang des Antragstellers. Die Beteiligten lehnen den Vergleichsvorschlag jeweils ab.")
    add_para(doc, "")
    add_para(doc, "Sodann ergeht der Beschluss:")
    add_para(doc, "")
    add_para(doc, "Die muendliche Verhandlung wird geschlossen. Die Entscheidung wird verkuendet am 14.11.2022 (Verkuendung in Abwesenheit; Zustellung).")
    add_para(doc, "")
    add_para(doc, "Vorgelesen, genehmigt:")
    add_para(doc, "")
    add_para(doc, "Dr. Pirckheimer                Manuel Brueckl")
    add_para(doc, "Vorsitzender                   Urkundsbeamter")
    doc.save(OUT / "Sitzungsprotokoll_OLG_18_10_2022.docx")


def build_aktenvermerk_telefonat():
    doc = base_doc("Aktenvermerk Telefonat 19.05.2021")
    add_para(doc, "Soell Roedelsteiner und Partner mbB", bold=True, align=WD_ALIGN_PARAGRAPH.CENTER)
    add_para(doc, "Karolinenstr. 27, 90402 Nuernberg", align=WD_ALIGN_PARAGRAPH.CENTER)
    add_para(doc, "")
    add_heading(doc, "Aktenvermerk - Telefonat", level=1)
    add_para(doc, "Aktenzeichen: 0918-2021/VA")
    add_para(doc, "Bearbeiterin: RAin Helene Soell-Roedelsteiner")
    add_para(doc, "Datum: 19.05.2021, 15:42 Uhr")
    add_para(doc, "Gespraechspartnerin: Frau Leonie Schaefer (Anruferin)")
    add_para(doc, "Dauer: 22 Minuten")
    add_para(doc, "")
    add_heading(doc, "Anlass", level=2)
    add_para(doc, "Frau Schaefer hat heute Mittag die Scheidungsantragsschrift ihres Ehemannes durch den Gerichtsvollzieher des AG Nuernberg-Fuerth zugestellt erhalten. Sie ist nach eigener Aussage 'fassungslos', aber gleichzeitig 'erleichtert, dass es nun einen formellen Schritt gibt'. Sie habe seit Jahren mit dem Antrag gerechnet.")
    add_para(doc, "")
    add_heading(doc, "Wesentliche Punkte", level=2)
    add_para(doc, "1. Die Antragsgegnerin moechte den Versorgungsausgleich in voller Hoehe durchfuehren lassen.")
    add_para(doc, "2. Sie ist Alleinerbin ihres Onkels Theodor Winterstein (verstorben 14.03.2019); das Vermoegen liege bei ca. 6,9 Mio. EUR und sei zum groessten Teil Immobilien-gebunden.")
    add_para(doc, "3. Der Ehemann habe sie im November 2020 zu einem Notartermin gebeten, in dem ein vollstaendiger Verzicht auf VA und Zugewinn angeregt worden sei. Sie habe diesen Verzicht abgelehnt.")
    add_para(doc, "4. Sie habe die Erbschaft 'aus Pietaet' nicht in der Beziehung thematisiert; auch habe sie damit nicht die gemeinsame Lebensplanung umgekrempelt.")
    add_para(doc, "5. Sie habe Pflichtteilsanspruechen gegen sich; ihre Cousine Hella Winterstein (Tochter des verstorbenen Onkels aus erster Ehe) habe diese am 16.06.2021 ueber Rechtsanwalt Wallner geltend gemacht (Schreiben siehe email).")
    add_para(doc, "6. Sie sei bereit, das Vermoegen offen zu legen; sie habe keine Geheimnisse, aber sie wolle nicht durch ihr Vermoegen 'bestraft' werden.")
    add_para(doc, "")
    add_heading(doc, "Vereinbartes Vorgehen", level=2)
    add_para(doc, "Termin Erstgespraech: 22.05.2021, 10:00 Uhr.")
    add_para(doc, "Die Mandantin bringt mit: Antragsschrift Vorndran; Erbschein AG Bamberg vom 02.09.2019; Erbschaftsteuerbescheid; Personalausweis; Heiratsurkunde.")
    add_para(doc, "Vollmachtsformular wird im Termin unterzeichnet.")
    add_para(doc, "")
    add_para(doc, "Nuernberg, 19.05.2021")
    add_para(doc, "Helene Soell-Roedelsteiner")
    doc.save(OUT / "Aktenvermerk_Telefonat_19_05_2021.docx")


if __name__ == "__main__":
    build_ag_beschluss()
    build_olg_beschluss()
    build_beschwerdebegruendung_vorndran()
    build_beschwerdeerwiderung_soell()
    build_notarvereinbarung()
    build_vollmacht_bgh()
    build_sitzungsprotokoll_olg()
    build_aktenvermerk_telefonat()
    print("OK")
