#!/usr/bin/env python3
"""Themenprofile fuer Werkstatt- und Schnellstart-Prompts.

Die Profile liefern fachliche Anker fuer den Generator. Sie sind bewusst
konservativ: Nur bekannte, allgemein belastbare Normen und Entscheidungen
werden verwendet. Der Generator mischt diese Profile mit den vorhandenen
Plugin-Manifesten, README-Texten und Skill-Beschreibungen.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class ThemenProfil:
    key: str
    label: str
    rolle: str
    normen: tuple[str, ...]
    entscheidungen: tuple[str, ...]
    stationen: tuple[str, ...]
    pruefraster: tuple[str, ...]
    stop: tuple[str, ...]
    skelette: tuple[str, ...] = field(default_factory=tuple)


PROFILE: tuple[ThemenProfil, ...] = (
    ThemenProfil(
        key="arbeits",
        label="Arbeitsrecht",
        rolle="Arbeitsrechtlicher Bearbeiter fuer Individual- und Kollektivarbeitsrecht mit Fokus auf Fristen, Form, Darlegungslast und verwertbare Prozess- oder Vertragsprodukte.",
        normen=(
            "KSchG Paragraf 1: soziale Rechtfertigung ordentlicher Kuendigungen.",
            "KSchG Paragraf 4 und Paragraf 7: Dreiwochenfrist und Wirksamkeitsfiktion.",
            "BGB Paragraf 611a: Arbeitsvertrag und Weisungsgebundenheit.",
            "BGB Paragraf 623: Schriftform fuer Kuendigung und Aufhebungsvertrag.",
            "TzBfG Paragraf 14 bis Paragraf 17: Befristung, Schriftform, Rechtsfolge und Befristungskontrollklage.",
            "BetrVG Paragraf 102: Anhoerung des Betriebsrats vor Kuendigung.",
        ),
        entscheidungen=(
            "BVerfG, Beschluss vom 06.06.2018 - 1 BvL 7/14 und 1 BvR 1375/14: Vorbeschaeftigungsverbot des TzBfG bleibt verfassungskonform, verlangt aber verfassungskonforme Begrenzung in atypischen Faellen.",
            "BAG, Urteil vom 27.02.1985 - GS 1/84: allgemeiner Weiterbeschaeftigungsanspruch nach obsiegendem erstinstanzlichem Kuendigungsschutzurteil.",
            "BAG, Urteil vom 24.08.2023 - 2 AZR 17/23: Kuendigungsschutzpruefung verlangt substantiierte Tatsachen zum Kuendigungsgrund und zur Interessenabwaegung.",
            "ArbG Berlin, Urteil vom 28.09.2021 - 36 Ca 15296/20: einfache elektronische Signatur wahrt die Schriftform einer Befristung nicht.",
            "LAG Berlin-Brandenburg, Urteil vom 16.03.2022 - 23 Sa 1133/21: Scan der Unterschrift wahrt TzBfG-Schriftform nicht und wird nach Arbeitsaufnahme nicht rueckwirkend geheilt.",
            "ArbG Gera, Urteil vom 07.03.2024 - 2 Ca 936/23: echte qualifizierte elektronische Signatur kann TzBfG-Schriftform wahren.",
        ),
        stationen=(
            "Mandat und Frist: Kuendigung, Befristungsende, Zugang, Betriebsratsdatum und Klageziel kalendarisch sichern.",
            "Status und Betrieb: Arbeitnehmerstellung, Betriebszugehoerigkeit, Wartezeit, Betriebsrat und Tarifbindung klaeren.",
            "Form und Zugang: Originalform, elektronische Form, Zugangsnachweis, Botenbeweis und Personalaktenbelege pruefen.",
            "Materielle Pruefung: Kuendigungsgrund, Befristungsgrund, Annahmeverzug, Urlaub, Zeugnis und Vergleichsfenster trennen.",
            "Arbeitsprodukt: Klage, Erwiderung, Vergleichsvorschlag, HR-Memo oder Vertragskorrektur in ausformulierten Saetzen erstellen.",
        ),
        pruefraster=(
            "Welche arbeitsrechtliche Massnahme ist angegriffen oder vorzubereiten.",
            "Welche Ausschluss- oder Klagefrist laeuft und ab welchem Ereignis.",
            "Welche Form ist Wirksamkeitsvoraussetzung und welches Beweismittel traegt sie.",
            "Welche Tatsachen traegt der Arbeitgeber, welche der Arbeitnehmer.",
            "Welche Nebenpunkte muessen in Vergleich oder Tenor mitgeregelt werden.",
        ),
        stop=(
            "Frist laeuft binnen drei Arbeitstagen ab und Unterlagen fehlen.",
            "Betriebsratsanhoerung, Massenentlassung, Schwangerschaft, Schwerbehinderung oder Compliance-Verdacht ist ungeklaert.",
            "Befristung wurde nicht in Papieroriginal oder echter qualifizierter elektronischer Signatur geschlossen.",
        ),
        skelette=(
            "Klageantrag: Es wird festgestellt, dass das Arbeitsverhaeltnis der Parteien durch die Kuendigung vom [Datum] nicht aufgeloest worden ist.",
            "Befristungsantrag: Es wird festgestellt, dass das Arbeitsverhaeltnis nicht aufgrund der Befristung vom [Datum] mit Ablauf des [Datum] geendet hat.",
            "Mandantenmemo: Die naechste Handlung ist [Klage/Antwort/Vergleich], weil [Frist/Form/Risiko] den weiteren Verlauf bestimmt.",
        ),
    ),
    ThemenProfil(
        key="miet",
        label="Miet- und Wohnungseigentumsrecht",
        rolle="Mietrechtlicher Bearbeiter fuer Wohnraum, Gewerberaum, Betriebskosten, Maengel, Kuendigung, Raeumung und WEG-Konflikte.",
        normen=(
            "BGB Paragraf 535: Hauptpflichten aus dem Mietvertrag.",
            "BGB Paragraf 536: Mietminderung bei Sach- und Rechtsmaengeln.",
            "BGB Paragraf 543 und Paragraf 569: ausserordentliche Kuendigung und Wohnraumschutz.",
            "BGB Paragraf 573: berechtigtes Interesse an ordentlicher Wohnraumkuendigung.",
            "GVG Paragraf 23 Nummer 2a: Wohnraummietsachen streitwertunabhaengig beim Amtsgericht.",
            "WEG Paragraf 18 und Paragraf 44: Verwaltung, Beschlussklage und gerichtliche Kontrolle.",
        ),
        entscheidungen=(
            "BGH, Urteil vom 18.03.2015 - VIII ZR 185/14: formularmaessige Quotenabgeltungsklauseln in Wohnraummietvertraegen sind unwirksam.",
            "BGH, Urteil vom 18.03.2015 - VIII ZR 242/13: Schoenheitsreparaturen bei unrenoviert ueberlassener Wohnung koennen formularmaessig nicht ohne Ausgleich ueberwaelzt werden.",
            "BGH, Urteil vom 20.09.2006 - VIII ZR 103/06: Betriebskostenabrechnung muss geordnet und nachvollziehbar sein.",
            "BGH, Urteil vom 04.05.2011 - VIII ZR 195/10: Eigenbedarf verlangt nachvollziehbaren Nutzungswunsch und Interessenabwaegung.",
            "BGH, Urteil vom 10.10.2012 - VIII ZR 107/12: Zahlungsverzug kann fristlose Kuendigung tragen, Schonfristzahlung wirkt nur begrenzt.",
        ),
        stationen=(
            "Vertrag und Objekt: Wohnraum, Gewerberaum oder WEG-Bezug, Parteien, Mietbeginn, Miethoehe und Klauseln erfassen.",
            "Zahlung und Abrechnung: Rueckstaende, Betriebskosten, Vorauszahlungen, Kaution und Verjaehrung rechnerisch pruefen.",
            "Mangel und Nutzung: Anzeige, Beweis, Minderungsquote, Zurueckbehaltung und Instandsetzung trennen.",
            "Kuendigung und Raeumung: Kuendigungsgrund, Fristen, Schutzvorschriften, Amtsgerichtszustaendigkeit und Vollstreckung abbilden.",
            "WEG-Beschluss und Verwaltung: Beschluss, Einladungsfehler, Beschlusskompetenz, ordnungsmaessige Verwaltung und Klagefrist pruefen.",
        ),
        pruefraster=(
            "Ist es Wohnraum, Gewerberaum oder Wohnungseigentum.",
            "Welche Forderung oder Pflicht ist faellig und wie wird sie belegt.",
            "Welche formellen Anforderungen gelten fuer Kuendigung, Abrechnung oder Beschluss.",
            "Welche Einwendungen sind rechtzeitig und beweisbar.",
            "Welches Gericht und welches Verfahren sind sachlich richtig.",
        ),
        stop=(
            "Raeumungsfrist oder Vollstreckungsschutz steht unmittelbar bevor.",
            "Wohnraummiete wird faelschlich nach Streitwert zum Landgericht geroutet.",
            "Betriebskostenabrechnung oder WEG-Beschluss ist rechnerisch nicht nachvollziehbar.",
        ),
    ),
    ThemenProfil(
        key="famil",
        label="Familienrecht",
        rolle="Familienrechtlicher Bearbeiter fuer Scheidung, Unterhalt, Kindschaft, Versorgungsausgleich und vermoegensrechtliche Folgesachen.",
        normen=(
            "BGB Paragraf 1565: Scheitern der Ehe als Scheidungsvoraussetzung.",
            "BGB Paragraf 1601 und Paragraf 1610: Verwandtenunterhalt und Mass des Unterhalts.",
            "BGB Paragraf 1612a: Mindestunterhalt minderjaehriger Kinder.",
            "BGB Paragraf 1671 und Paragraf 1684: elterliche Sorge und Umgang.",
            "FamFG Paragraf 38: Beschlussform und Begruendung.",
            "VersAusglG Paragraf 1 und Paragraf 10: Grundsatz und interne Teilung.",
        ),
        entscheidungen=(
            "BGH, Beschluss vom 15.02.2017 - XII ZB 201/16: Wechselmodell kann auch gegen den Willen eines Elternteils angeordnet werden, wenn es dem Kindeswohl entspricht.",
            "BGH, Beschluss vom 27.11.2019 - XII ZB 512/18: Kindesunterhalt verlangt konkrete Ermittlung von Einkommen, Bedarf und Leistungsfaehigkeit.",
            "BGH, Beschluss vom 18.01.2017 - XII ZB 118/16: Auskunft und Belegvorlage sind Grundlage tragfaehiger Unterhaltsberechnung.",
            "BGH, Beschluss vom 26.05.2021 - XII ZB 164/20: Unterhalt bei selbstaendiger Taetigkeit verlangt Plausibilisierung mehrerer Jahre.",
            "BGH, Beschluss vom 16.09.2020 - XII ZB 499/19: Versorgungsausgleich erfordert korrekte Ehezeit und Anrechtsbewertung.",
        ),
        stationen=(
            "Familienstand und Verfahrensart: Scheidung, Unterhalt, Sorge, Umgang oder Versorgungsausgleich trennen.",
            "Einkommen und Bedarf: Einkuenfte, Abzuege, Tabellenbedarf, Selbstbehalt und Mangelfall rechnerisch aufbereiten.",
            "Kindschaft: Kindeswohl, Bindungen, Betreuung, Wille, Foerderprinzip und Kontinuitaet dokumentieren.",
            "Folgesachen: Versorgungsausgleich, Zugewinn, Ehewohnung, Hausrat und Verfahrensverbund ordnen.",
            "Arbeitsprodukt: Antrag, Stufenantrag, Beschlussentwurf, Vergleich oder Berechnungstabelle ausformulieren.",
        ),
        pruefraster=(
            "Welche Familiensache ist rechtshaengig oder vorzubereiten.",
            "Welche Auskunft und welche Belege fehlen.",
            "Welche Berechnungsvariante ist fuer Unterhalt oder Versorgungsausgleich tragend.",
            "Welche Kindeswohlkriterien sind konkret belegt.",
            "Welche Entscheidung kann ohne weitere Aufklaerung nicht ergehen.",
        ),
        stop=(
            "Kindeswohlgefaehrdung, Gewalt, Entfuehrungsrisiko oder Schutzanordnung steht im Raum.",
            "Unterhaltsberechnung beruht auf ungeprueften Tabellenwerten oder fehlenden Einkommensbelegen.",
            "Versorgungsausgleichsdaten sind unvollstaendig oder Ehezeit ist streitig.",
        ),
    ),
    ThemenProfil(
        key="straf",
        label="Strafrecht und Strafverfahren",
        rolle="Strafrechtlicher Bearbeiter fuer Ermittlungsverfahren, Anklage, Hauptverhandlung, Rechtsfolgen und Verteidigungsschrift.",
        normen=(
            "StPO Paragraf 152 Absatz 2: Legalitaetsprinzip und Anfangsverdacht.",
            "StPO Paragraf 160: Pflicht zur Erforschung belastender und entlastender Umstaende.",
            "StPO Paragraf 170: Abschlussentscheidung der Staatsanwaltschaft.",
            "StPO Paragraf 261: freie richterliche Beweiswuerdigung.",
            "StPO Paragraf 267: Urteilsgruende im Strafurteil.",
            "StGB Paragraf 46: Strafzumessung.",
        ),
        entscheidungen=(
            "BGH, Urteil vom 30.07.1999 - 1 StR 618/98: Aussage-gegen-Aussage verlangt besonders sorgfaeltige Gesamtwuerdigung.",
            "BGH, Urteil vom 29.07.1998 - 1 StR 94/98: Konstanz, Entstehung und Belastungsmotive sind bei Aussageanalyse zu wuerdigen.",
            "BGH, Beschluss vom 10.01.2017 - 4 StR 247/16: Beweiswuerdigung darf keine Luecken und Widersprueche offenlassen.",
            "BVerfG, Beschluss vom 19.03.2013 - 2 BvR 2628/10: Verstaendigung im Strafverfahren verlangt Transparenz und Dokumentation.",
            "BGH, Beschluss vom 28.11.2018 - 5 StR 566/18: Strafzumessung muss schuldangemessen begruendet werden.",
        ),
        stationen=(
            "Tatkomplex und Verfahrensstand: Anzeige, Beschuldigtenstatus, Anklage, Strafbefehl oder Urteil erfassen.",
            "Beweise und Einlassung: Zeugen, Urkunden, Sachverstaendige, digitale Spuren und Schweigerechte trennen.",
            "Tatbestand: objektive und subjektive Merkmale, Konkurrenzen, Versuch, Teilnahme und Rechtfertigung pruefen.",
            "Prozessuales: Zuständigkeit, Verwertbarkeit, Fristen, Pflichtverteidigung und Antraege vorbereiten.",
            "Rechtsfolge: Strafrahmen, Milderung, Nebenfolgen, Bewaehrung und Einstellungschancen ausarbeiten.",
        ),
        pruefraster=(
            "Welcher Tatvorwurf wird mit welcher Norm verbunden.",
            "Welche Tatsache wird durch welches Beweismittel getragen.",
            "Welche Beweisverwertungs- oder Aussageprobleme sind entscheidend.",
            "Welche Einlassungs- oder Antragsstrategie ist prozessual sauber.",
            "Welche Rechtsfolge ist nach Schuld, Vorleben und Nachtatverhalten naheliegend.",
        ),
        stop=(
            "Haft, Durchsuchung, Beschlagnahme oder Aussageentscheidung steht unmittelbar an.",
            "Pflichtverteidigung liegt nahe und ist nicht geklaert.",
            "Ein Geständnis oder eine Verstaendigung wird ohne Aktenkenntnis erwogen.",
        ),
    ),
    ThemenProfil(
        key="datenschutz",
        label="Datenschutzrecht",
        rolle="Datenschutzrechtlicher Bearbeiter fuer Verantwortliche, Auftragsverarbeitung, Betroffenenrechte, Datenschutzaufsicht und Datenpannen.",
        normen=(
            "DSGVO Artikel 5: Grundsaetze der Verarbeitung personenbezogener Daten.",
            "DSGVO Artikel 6: Rechtmaessigkeit der Verarbeitung.",
            "DSGVO Artikel 12 bis Artikel 15: Transparenz, Auskunft und Kommunikation.",
            "DSGVO Artikel 28: Auftragsverarbeitung.",
            "DSGVO Artikel 32: Sicherheit der Verarbeitung.",
            "DSGVO Artikel 33 und Artikel 34: Meldung von Verletzungen des Schutzes personenbezogener Daten.",
        ),
        entscheidungen=(
            "EuGH, Urteil vom 16.07.2020 - C-311/18: Schrems II verlangt tragfaehige Pruefung internationaler Datentransfers.",
            "EuGH, Urteil vom 04.05.2023 - C-300/21: immaterieller Schadensersatz nach DSGVO verlangt Schaden, Verstoss und Kausalitaet.",
            "EuGH, Urteil vom 05.12.2023 - C-683/21: Verantwortlichkeit setzt Einfluss auf Zwecke und Mittel der Verarbeitung voraus.",
            "EuGH, Urteil vom 07.12.2023 - C-634/21: automatisiertes Scoring kann an Artikel 22 DSGVO scheitern.",
            "BVerfG, Urteil vom 15.12.1983 - 1 BvR 209/83 u.a.: informationelle Selbstbestimmung als verfassungsrechtlicher Leitanker.",
        ),
        stationen=(
            "Verarbeitungsvorgang und Rollen bestimmen.",
            "Rechtsgrundlage, Zweckbindung und Datenminimierung pruefen.",
            "Informationspflichten, Betroffenenrechte und Fristen strukturieren.",
            "Technische und organisatorische Massnahmen sowie Auftragsverarbeitung pruefen.",
            "Datenpanne, Aufsichtsverfahren, Schadensersatz und Loeschkonzept bearbeiten.",
        ),
        pruefraster=(
            "Wer entscheidet ueber Zweck und Mittel.",
            "Welche Datenkategorie und welcher Zweck liegen vor.",
            "Welche Rechtsgrundlage traegt die Verarbeitung.",
            "Welche Betroffenenrechte und Fristen laufen.",
            "Welche Dokumentation muss vorliegen.",
        ),
        stop=(
            "Meldepflichtige Datenpanne mit laufender Frist.",
            "Besondere Kategorien personenbezogener Daten ohne belastbare Rechtsgrundlage.",
            "Internationaler Transfer ohne Transfergrundlage.",
        ),
    ),
    ThemenProfil(
        key="insolvenz",
        label="Insolvenz- und Sanierungsrecht",
        rolle="Insolvenzrechtlicher Bearbeiter fuer Krisenfrueherkennung, Insolvenzantrag, Forderungsanmeldung, Anfechtung, Plan und Sanierung.",
        normen=(
            "InsO Paragraf 17: Zahlungsunfaehigkeit.",
            "InsO Paragraf 18: drohende Zahlungsunfaehigkeit.",
            "InsO Paragraf 19: Ueberschuldung.",
            "InsO Paragraf 129 bis Paragraf 147: Insolvenzanfechtung.",
            "InsO Paragraf 174: Forderungsanmeldung.",
            "StaRUG Paragraf 1: Krisenfrueherkennungspflichten.",
        ),
        entscheidungen=(
            "BGH, Urteil vom 24.05.2005 - IX ZR 123/04: Zahlungsunfaehigkeit ist regelmaessig bei Liquiditaetsluecke von zehn Prozent anzunehmen.",
            "BGH, Urteil vom 19.12.2017 - II ZR 88/16: Geschaeftsleiterpflichten in Krise und Insolvenzreife sind streng zu dokumentieren.",
            "BGH, Urteil vom 06.05.2021 - IX ZR 72/20: Vorsatzanfechtung verlangt Gesamtwuerdigung der Indizien.",
            "BGH, Urteil vom 10.02.2022 - IX ZR 148/19: Sanierungsversuch kann Vorsatzanfechtung beeinflussen, wenn er tragfaehig ist.",
            "BGH, Urteil vom 28.06.2012 - IX ZR 219/10: Bargeschaeftsnaehe kann Anfechtungsrisiken begrenzen.",
        ),
        stationen=(
            "Krise feststellen: Liquiditaetsstatus, Faelligkeiten, Fortbestehensprognose und Zahlungsstockung trennen.",
            "Pflichten zuordnen: Geschaeftsleitung, Glaeubiger, Berater, Insolvenzgericht und Verwalterrolle klären.",
            "Antrag und Sicherung: Insolvenzantrag, vorlaeufige Massnahmen, Masseerhalt und Kommunikation vorbereiten.",
            "Forderung und Tabelle: Anmeldung, Bestreiten, Feststellung, Sicherheiten und Aussonderung aufbereiten.",
            "Anfechtung und Plan: Rechtshandlung, Kenntnis, Gläubigerbenachteiligung, Sanierungsvergleich und Planlogik pruefen.",
        ),
        pruefraster=(
            "Liegt Zahlungsunfaehigkeit, drohende Zahlungsunfaehigkeit oder Ueberschuldung vor.",
            "Welche Frist oder Pflicht trifft welche Person.",
            "Welche Zahlung oder Sicherheit ist anfechtbar.",
            "Welche Forderung ist mit welchem Rang anzumelden.",
            "Welche Sanierungsoption ist realistisch belegbar.",
        ),
        stop=(
            "Insolvenzantragspflicht kann laufen.",
            "Masseschmaelernde Zahlung steht bevor.",
            "Haftung der Geschaeftsleitung ist nicht geprueft.",
        ),
    ),
    ThemenProfil(
        key="steuer",
        label="Steuerrecht",
        rolle="Steuerrechtlicher Bearbeiter fuer Veranlagung, Einspruch, Betriebspruefung, internationale Besteuerung und Gestaltungsrisiken.",
        normen=(
            "AO Paragraf 85: Legalitaet und Gleichmaessigkeit der Besteuerung.",
            "AO Paragraf 88: Amtsermittlung.",
            "AO Paragraf 173: Aufhebung oder Aenderung wegen neuer Tatsachen.",
            "EStG Paragraf 2: Einkunftsarten und Einkommensermittlung.",
            "EStG Paragraf 49: beschraenkte Steuerpflicht.",
            "FGO Paragraf 76: Sachaufklaerung im Finanzgerichtsverfahren.",
        ),
        entscheidungen=(
            "BFH, Urteil vom 04.11.2021 - VI R 22/19: Doppelbesteuerungsabkommen begruenden grundsaetzlich keine Steuerpflicht, sondern begrenzen vorhandene nationale Besteuerung.",
            "BVerfG, Beschluss vom 08.07.2021 - 1 BvR 2237/14 und 1 BvR 2422/17: Vollverzinsung nach AO war ab 2014 verfassungswidrig.",
            "BFH, Urteil vom 21.06.2012 - V R 20/11: Vorsteuerabzug verlangt ordnungsgemaesse Rechnung und Leistungsbezug.",
            "EuGH, Urteil vom 06.07.2006 - C-439/04 und C-440/04: Kittel-Rechtsprechung zum Vorsteuerabzug bei Kenntnis von Umsatzsteuerbetrug.",
            "EuGH, Urteil vom 21.06.2012 - C-80/11 und C-142/11: Mahageben und David begrenzen ueberzogene Nachweispflichten beim Vorsteuerabzug.",
        ),
        stationen=(
            "Steuerart, Zeitraum, Bescheidlage und Frist bestimmen.",
            "Nationalen Tatbestand, persoenliche Steuerpflicht und Einkunfts- oder Umsatzlogik pruefen.",
            "Verfahrensrecht: Einspruch, Aussetzung, Aenderungsnorm und Festsetzungsfrist bearbeiten.",
            "Belege, Buchfuehrung, Rechnung, DBA und unionsrechtliche Sperren trennen.",
            "Arbeitsprodukt: Einspruch, Klage, Stellungnahme, Risikomatrix oder Berechnung erstellen.",
        ),
        pruefraster=(
            "Welche Steuerart und welcher Zeitraum sind betroffen.",
            "Welche nationale Norm begruendet die Steuerpflicht.",
            "Welche Korrektur- oder Rechtsbehelfsfrist laeuft.",
            "Welche Belege tragen die Besteuerungsgrundlage.",
            "Welche DBA- oder Unionsrechtsfrage begrenzt die Besteuerung.",
        ),
        stop=(
            "Einspruchs- oder Klagefrist laeuft ab.",
            "Steuerstrafrechtlicher Anfangsverdacht steht im Raum.",
            "DBA- oder Quellensteuerfrage kann nicht ohne Belege entschieden werden.",
        ),
    ),
    ThemenProfil(
        key="gesellschaft",
        label="Gesellschaftsrecht",
        rolle="Gesellschaftsrechtlicher Bearbeiter fuer GmbH, AG, Personengesellschaften, Organpflichten, Beschlussmaengel und Transaktionen.",
        normen=(
            "BGB Paragraf 705: Gesellschaftsvertrag der Gesellschaft bürgerlichen Rechts.",
            "HGB Paragraf 105: offene Handelsgesellschaft.",
            "GmbHG Paragraf 13: Rechtsnatur der GmbH.",
            "GmbHG Paragraf 15: Uebertragung von Geschaeftsanteilen.",
            "GmbHG Paragraf 43: Sorgfalt und Verantwortlichkeit der Geschaeftsfuehrer.",
            "AktG Paragraf 93: Sorgfaltspflicht und Verantwortlichkeit des Vorstands.",
        ),
        entscheidungen=(
            "BGH, Urteil vom 29.01.2001 - II ZR 331/00: ARAG/Garmenbeck praegt die Pflicht zur Verfolgung von Organhaftungsanspruechen.",
            "BGH, Urteil vom 04.07.2005 - II ZR 354/03: Trihotel zur Existenzvernichtungshaftung.",
            "BGH, Urteil vom 10.05.2016 - II ZR 342/14: Gesellschafterliste und Legitimationswirkung sind fuer GmbH-Rechte zentral.",
            "BGH, Urteil vom 20.09.2011 - II ZR 234/09: Beschlussmaengel in der GmbH folgen eigenstaendiger gesellschaftsrechtlicher Dogmatik.",
            "BGH, Urteil vom 26.01.2009 - II ZR 260/07: Treuepflichten begrenzen gesellschaftsrechtliche Rechtsausuebung.",
        ),
        stationen=(
            "Gesellschaftsform, Registerlage, Beteiligungen und Organe feststellen.",
            "Satzung, Gesellschaftervereinbarung, Beschluss und Vertretung trennen.",
            "Organpflichten, Treuepflichten, Zustimmungserfordernisse und Haftung pruefen.",
            "Transaktionsschritte, Notarform, Closing-Bedingungen und Registervollzug planen.",
            "Arbeitsprodukt: Beschlussvorschlag, Organmemo, Anteilsuebertragungsvertrag oder Klageentwurf erstellen.",
        ),
        pruefraster=(
            "Welche Gesellschaftsform und welche Rechtsquelle bestimmen den Fall.",
            "Wer ist Organ, Gesellschafter, Vertreter oder wirtschaftlich Berechtigter.",
            "Welche Beschluss- oder Formanforderung ist Wirksamkeitsvoraussetzung.",
            "Welche Haftungsnorm und welcher Schaden sind konkret.",
            "Welcher Vollzugsschritt ist noch offen.",
        ),
        stop=(
            "Notarielle Form oder Registerfrist ist ungeklärt.",
            "Organhaftung, Insolvenznaehe oder Interessenkonflikt steht im Raum.",
            "Gesellschafterliste, Vollmacht oder Beschlussfassung ist widerspruechlich.",
        ),
    ),
    ThemenProfil(
        key="verfass",
        label="Verfassungsrecht",
        rolle="Verfassungsrechtlicher Bearbeiter fuer Grundrechte, Staatsorganisationsrecht, Verfassungsbeschwerde, Normenkontrolle und Verhaeltnismaessigkeit.",
        normen=(
            "GG Artikel 1 Absatz 1: Menschenwuerdebindung aller Staatsgewalt.",
            "GG Artikel 2 Absatz 1: allgemeine Handlungsfreiheit.",
            "GG Artikel 3 Absatz 1: Gleichheitssatz.",
            "GG Artikel 12 Absatz 1: Berufsfreiheit.",
            "GG Artikel 14 Absatz 1: Eigentum und Inhaltsbestimmung.",
            "BVerfGG Paragraf 90: Verfassungsbeschwerde.",
        ),
        entscheidungen=(
            "BVerfG, Urteil vom 15.01.1958 - 1 BvR 400/51: Lueth begruendet objektive Wertordnung und mittelbare Drittwirkung der Grundrechte.",
            "BVerfG, Urteil vom 11.06.1958 - 1 BvR 596/56: Apothekenurteil strukturiert Eingriffe in die Berufsfreiheit.",
            "BVerfG, Beschluss vom 14.02.1973 - 1 BvR 112/65: Soraya staerkt Persoenlichkeitsrecht und richterliche Rechtsfortbildung.",
            "BVerfG, Urteil vom 15.12.1983 - 1 BvR 209/83 u.a.: Volkszaehlung entwickelt informationelle Selbstbestimmung.",
            "BVerfG, Beschluss vom 24.05.2006 - 2 BvR 669/04: Verhaeltnismaessigkeit verlangt legitimen Zweck, Geeignetheit, Erforderlichkeit und Angemessenheit.",
        ),
        stationen=(
            "Beschwerdegegenstand, Hoheitsakt, Beschwerdefuehrer und Frist feststellen.",
            "Zulaessigkeit: Rechtswegerschoepfung, Subsidiaritaet, Beschwerdebefugnis und Form pruefen.",
            "Schutzbereich, Eingriff, Schranke und Schranken-Schranke aufbauen.",
            "Verhaeltnismaessigkeit mit milderen Mitteln, Gewichtung und Evidenzkontrolle ausarbeiten.",
            "Arbeitsprodukt: Verfassungsbeschwerde, Stellungnahme, Normenkontrollskizze oder Tenorvorschlag.",
        ),
        pruefraster=(
            "Welches Grundrecht oder Organrecht ist betroffen.",
            "Welcher Hoheitsakt und welche Frist sind entscheidend.",
            "Ist der Rechtsweg erschoepft und die Subsidiaritaet gewahrt.",
            "Welcher Eingriff wird durch welche Schranke gerechtfertigt.",
            "Ist die Massnahme im engeren Sinne angemessen.",
        ),
        stop=(
            "Frist nach BVerfGG laeuft.",
            "Rechtswegerschoepfung oder Subsidiaritaet ist nicht belegt.",
            "Tatsachenbasis fuer Grundrechtsgewichtung fehlt.",
        ),
    ),
    ThemenProfil(
        key="versicherung",
        label="Versicherungsrecht",
        rolle="Versicherungsrechtlicher Bearbeiter fuer Deckungspruefung, Leistungsfall, Obliegenheiten, Ruecktritt, Anfechtung, Beratungspflichten und Aufsichtsbezug.",
        normen=(
            "VVG Paragraf 1: vertragstypische Pflichten aus dem Versicherungsvertrag.",
            "VVG Paragraf 19: vorvertragliche Anzeigepflicht und Rechtsfolgen.",
            "VVG Paragraf 28: Obliegenheitsverletzung nach Vertragsschluss.",
            "VVG Paragraf 61: Beratungspflichten des Versicherungsvermittlers.",
            "VVG Paragraf 86: Uebergang von Ersatzanspruechen.",
            "BGB Paragraf 305 bis Paragraf 310: AGB-Kontrolle von Versicherungsbedingungen.",
        ),
        entscheidungen=(
            "BGH, Urteil vom 22.06.2011 - IV ZR 225/10: Beratungspflichten im Versicherungsvertrieb verlangen anlassbezogene, dokumentierbare Bedarfsermittlung.",
            "BGH, Urteil vom 12.03.2014 - IV ZR 306/13: Obliegenheitsverletzungen sind nach Kausalitaet, Verschulden und Belehrung zu pruefen.",
            "BGH, Urteil vom 07.05.2014 - IV ZR 76/11: Versicherungsbedingungen sind aus Sicht eines durchschnittlichen Versicherungsnehmers auszulegen.",
            "BGH, Urteil vom 25.05.2016 - IV ZR 205/15: Ruecktritt wegen Anzeigepflichtverletzung verlangt saubere Risikofragen und Belehrung.",
            "BGH, Urteil vom 18.07.2018 - IV ZR 68/17: Leistungsfreiheit setzt konkrete vertragliche Obliegenheit und Rechtsfolgenbelehrung voraus.",
        ),
        stationen=(
            "Vertrag und Sparte: Versicherungsart, Versicherungsnehmer, versicherte Person, Risiko, Laufzeit und Bedingungen erfassen.",
            "Versicherungsfall: Eintritt, Anzeige, Schadenhoehe, Kausalitaet, Ausschluss und Beweislast ordnen.",
            "Obliegenheiten: vorvertragliche Anzeige, Gefahrerhoehung, Schadenanzeige, Mitwirkung und Rechtsfolgenbelehrung pruefen.",
            "Deckung und Regulierung: Leistungsentscheidung, Quote, Regress, Verjaehrung und Prozessrisiko ausarbeiten.",
            "Arbeitsprodukt: Deckungsmemo, Anspruchsschreiben, Ablehnungsschreiben, Vergleichsvorschlag oder Klageentwurf formulieren.",
        ),
        pruefraster=(
            "Welche Sparte und welche Bedingungen gelten.",
            "Ist der Versicherungsfall nach Zeit, Ort, Ursache und Schaden belegt.",
            "Welche Ausschluesse oder Obliegenheiten werden geltend gemacht.",
            "Welche Belehrung und Kausalitaet sind beweisbar.",
            "Welche Leistung oder Quote ist schluessig.",
        ),
        stop=(
            "Frist zur Schadenanzeige, Klage oder Deckungsablehnung laeuft.",
            "Arglist, Ruecktritt oder Anfechtung wird behauptet.",
            "Bedingungswerk oder Nachtrag fehlt.",
        ),
    ),
    ThemenProfil(
        key="liquiditaet",
        label="Liquiditaetsplanung",
        rolle="Liquiditaetsplanender Bearbeiter fuer Unternehmen, Geschaeftsleitung und Beratung mit Fokus auf Zahlungsfaehigkeit, Wochenplanung, Szenarien, Covenants und dokumentierte Anschlussentscheidungen.",
        normen=(
            "InsO Paragraf 17: Zahlungsunfaehigkeit als harte Grenze der Liquiditaetsplanung.",
            "InsO Paragraf 18: drohende Zahlungsunfaehigkeit als Sanierungs- und Planungswarnsignal.",
            "InsO Paragraf 19: Ueberschuldung bei juristischen Personen.",
            "StaRUG Paragraf 1: Krisenfrueherkennung und Krisenmanagement.",
            "GmbHG Paragraf 43: Sorgfaltspflichten der Geschaeftsfuehrung.",
            "AktG Paragraf 91 Absatz 2: Ueberwachungssystem fuer bestandsgefaehrdende Entwicklungen.",
        ),
        entscheidungen=(
            "BGH, Urteil vom 24.05.2005 - IX ZR 123/04: Zahlungsunfaehigkeit wird regelmaessig anhand einer erheblichen Liquiditaetsluecke beurteilt.",
            "BGH, Urteil vom 19.12.2017 - II ZR 88/16: Geschaeftsleiter muessen Krisenentscheidungen und Zahlungsverbote nachvollziehbar dokumentieren.",
            "BGH, Urteil vom 26.01.2017 - IX ZR 285/14: Liquiditaetsstatus und Zahlungsstockung sind nicht durch Hoffnung auf spaetere Mittelzufluesse zu ersetzen.",
            "BGH, Urteil vom 06.05.2021 - IX ZR 72/20: Indizien fuer Zahlungsunfaehigkeit und Gläubigerkenntnis sind im Zusammenhang zu wuerdigen.",
            "BGH, Urteil vom 10.02.2022 - IX ZR 148/19: Tragfaehige Sanierungsbemuehungen setzen ein belastbares Konzept und erkennbare Finanzierung voraus.",
        ),
        stationen=(
            "Datenraum: Bankkonten, offene Posten, Lohnsteuer, Sozialabgaben, Kreditlinien, Sicherheiten und Faelligkeiten einsammeln.",
            "Dreizehn-Wochen-Plan: Anfangsliquiditaet, sichere Zufluesse, unvermeidbare Abfluesse und freie Linien wochenweise darstellen.",
            "Stressszenarien: Zahlungsverzug von Kunden, Covenant-Bruch, Lieferantenstopp, Lohnlauf und Steuern separat simulieren.",
            "Insolvenznaehe: Zahlungsstockung, Zahlungsunfaehigkeit, drohende Zahlungsunfaehigkeit und Ueberschuldung getrennt dokumentieren.",
            "Anschlussentscheidung: Finanzierungsanfrage, Stundung, Gesellschafterbeitrag, Sanierungspfad oder Insolvenzantragspruefung formulieren.",
        ),
        pruefraster=(
            "Welche Zahlungen sind heute, sieben Tage, dreissig Tage und dreizehn Wochen faellig.",
            "Welche Zufluesse sind sicher, bedingt, streitig oder nur geplant.",
            "Welche Zahlungen duerfen aus Haftungsgruenden nicht mehr ohne Pruefung geleistet werden.",
            "Welche Krise wird durch welchen Status belegt.",
            "Welche Entscheidung der Geschaeftsleitung ist jetzt dokumentationspflichtig.",
        ),
        stop=(
            "Liquiditaetsluecke kann nicht binnen drei Wochen geschlossen werden.",
            "Lohnsteuer, Sozialversicherung oder Lohnlauf stehen ohne Deckung bevor.",
            "Geschaeftsleitung will Zahlungen priorisieren, ohne Insolvenzreife geprueft zu haben.",
        ),
    ),
    ThemenProfil(
        key="sozial",
        label="Sozialrecht",
        rolle="Sozialrechtlicher Bearbeiter fuer Verwaltungsverfahren, Widerspruch, Klage, Leistungsrecht, Krankenversicherung, Teilhabe, Erwerbsminderung und existenzsichernde Leistungen.",
        normen=(
            "SGB I Paragraf 39: Sozialleistungen als Anspruch bei Vorliegen der gesetzlichen Voraussetzungen.",
            "SGB X Paragraf 20: Amtsermittlung im Sozialverwaltungsverfahren.",
            "SGB X Paragraf 24: Anhoerung vor belastendem Verwaltungsakt.",
            "SGG Paragraf 87: Klagefrist.",
            "SGG Paragraf 103: Amtsermittlung im sozialgerichtlichen Verfahren.",
            "SGG Paragraf 86b: einstweiliger Rechtsschutz.",
        ),
        entscheidungen=(
            "BVerfG, Urteil vom 09.02.2010 - 1 BvL 1/09: existenzsichernde Leistungen muessen transparent und realitaetsgerecht bemessen sein.",
            "BVerfG, Urteil vom 05.11.2019 - 1 BvL 7/16: Sanktionen im Grundsicherungsrecht unterliegen strenger Verhaeltnismaessigkeitskontrolle.",
            "BVerfG, Beschluss vom 06.12.2005 - 1 BvR 347/98: lebensbedrohliche oder regelmaessig toedliche Erkrankungen koennen Leistungsansprueche der Krankenversicherung verfassungsrechtlich verdichten.",
            "BSG, Urteil vom 16.12.2008 - B 4 AS 48/07 R: Unterkunftskosten sind am konkreten Bedarf und an einem schluessigen Konzept zu messen.",
            "BSG, Urteil vom 02.09.2009 - B 6 KA 34/08 R: sozialrechtliche Sachverhaltsaufklaerung verlangt verwertbare medizinische und tatsaechliche Grundlagen.",
        ),
        stationen=(
            "Bescheidlage: Verwaltungsakt, Widerspruch, Klagefrist, Leistungstraeger und Leistungsart erfassen.",
            "Bedarf und Anspruch: persoenliche Voraussetzungen, Bedarf, Einkommen, Vermoegen, Mitwirkung und Ausschlussgruende pruefen.",
            "Medizin und Teilhabe: Befund, Gutachten, Leistungsbild, Erwerbsfaehigkeit und Rehabilitationsziel ordnen.",
            "Eilrechtsschutz: Anordnungsanspruch, Anordnungsgrund, Folgenabwaegung und Existenzsicherung darstellen.",
            "Arbeitsprodukt: Widerspruch, Klage, Eilantrag, Befundanforderung oder Vergleichsvorschlag ausformulieren.",
        ),
        pruefraster=(
            "Welcher Bescheid wird mit welchem Ziel angegriffen.",
            "Welche Frist laeuft und ist Vorverfahren erforderlich.",
            "Welche Anspruchsvoraussetzung ist durch welchen Beleg bewiesen.",
            "Welche medizinische oder wirtschaftliche Tatsache fehlt.",
            "Welche existenzielle Folge droht ohne Eilentscheidung.",
        ),
        stop=(
            "Existenzminimum, Krankenbehandlung oder Wohnungssicherung ist akut betroffen.",
            "Medizinische Unterlagen fehlen fuer eine tragende Leistungsbeurteilung.",
            "Frist oder Zugang des Bescheids ist unklar.",
        ),
    ),
    ThemenProfil(
        key="verwaltung",
        label="Verwaltungsrecht",
        rolle="Verwaltungsrechtlicher Bearbeiter fuer Verwaltungsakt, Widerspruch, Klage, Eilrechtsschutz, Ermessen, Satzungen und behördliche Verfahren.",
        normen=(
            "VwVfG Paragraf 35: Verwaltungsakt als zentrale Handlungsform.",
            "VwVfG Paragraf 28: Anhoerung Beteiligter.",
            "VwVfG Paragraf 40: Ermessen und Ermessensgrenzen.",
            "VwGO Paragraf 42: Anfechtungs- und Verpflichtungsklage.",
            "VwGO Paragraf 80 Absatz 5: Eilrechtsschutz gegen sofort vollziehbare Verwaltungsakte.",
            "VwGO Paragraf 123: einstweilige Anordnung.",
        ),
        entscheidungen=(
            "BVerfG, Beschluss vom 14.05.1985 - 2 BvR 397/82: effektiver Rechtsschutz verlangt eine tatsaechlich wirksame gerichtliche Kontrolle.",
            "BVerwG, Urteil vom 27.09.1978 - 7 C 79.76: Ermessensentscheidungen muessen Zweck, Grenzen und Abwaegung erkennen lassen.",
            "BVerwG, Urteil vom 17.02.1984 - 7 C 8.82: Nebenbestimmungen sind an ihrer gesetzlichen Grundlage und Verhaeltnismaessigkeit zu messen.",
            "BVerwG, Urteil vom 21.11.1986 - 8 C 127.84: Ruecknahme und Widerruf verlangen strikte Trennung der gesetzlichen Tatbestaende.",
            "BVerwG, Urteil vom 20.10.1989 - 7 C 87.87: Verwaltungsvollstreckung setzt wirksamen Grundverwaltungsakt und vollziehbare Pflicht voraus.",
        ),
        stationen=(
            "Verwaltungshandeln: Verwaltungsakt, Realakt, Satzung, Nebenbestimmung oder Vollstreckung erkennen.",
            "Zulaessigkeit: Statthafte Klageart, Klagebefugnis, Vorverfahren, Frist und Gericht bestimmen.",
            "Materielle Rechtmaessigkeit: Ermaechtigungsgrundlage, formelle Fehler, Tatbestand, Ermessen und Verhaeltnismaessigkeit pruefen.",
            "Eilrechtsschutz: aufschiebende Wirkung, Vollziehungsinteresse, Folgenabwaegung und Sicherungsanordnung strukturieren.",
            "Arbeitsprodukt: Widerspruch, Klage, Eilantrag, Bescheidpruefung oder Vergleichsvorschlag erstellen.",
        ),
        pruefraster=(
            "Welche Handlungsform liegt vor.",
            "Welche Klage- oder Antragsart ist statthaft.",
            "Welche formellen Fehler koennen geheilt werden und welche nicht.",
            "Welche Ermessensfehler oder Abwaegungsdefizite tragen den Angriff.",
            "Welche vorlaeufige Regelung ist im Eilverfahren erforderlich.",
        ),
        stop=(
            "Sofortvollzug oder Vollstreckung steht unmittelbar bevor.",
            "Rechtsbehelfsfrist ist unklar.",
            "Ermaechtigungsgrundlage oder Landesrecht fehlt.",
        ),
    ),
    ThemenProfil(
        key="vergabe",
        label="Vergaberecht",
        rolle="Vergaberechtlicher Bearbeiter fuer Ausschreibung, Rüge, Nachpruefungsverfahren, Zuschlagsverbot, Wertung und strategische Korrektur von Vergabefehlern.",
        normen=(
            "GWB Paragraf 97: Grundsaetze des Vergaberechts.",
            "GWB Paragraf 134: Informations- und Wartepflicht vor Zuschlag.",
            "GWB Paragraf 160: Nachpruefungsantrag und Rügeobliegenheit.",
            "VgV Paragraf 57: Ausschluss von Angeboten.",
            "VgV Paragraf 58: Zuschlag und Wertung.",
            "GWB Paragraf 168: Entscheidung der Vergabekammer.",
        ),
        entscheidungen=(
            "EuGH, Urteil vom 11.01.2005 - C-26/03: Stadt Halle begrenzt vergabefreie Inhouse-Vergaben.",
            "EuGH, Urteil vom 13.10.2005 - C-458/03: Parking Brixen konkretisiert Transparenzpflichten bei Konzessionen.",
            "EuGH, Urteil vom 19.06.2008 - C-454/06: Pressetext grenzt wesentliche Vertragsaenderungen nach Zuschlag ab.",
            "EuGH, Urteil vom 10.09.2009 - C-206/08: Eurawasser ordnet Dienstleistungskonzessionen anhand des Betriebsrisikos ein.",
            "BGH, Beschluss vom 08.02.2011 - X ZB 4/10: Vergabenachpruefung verlangt effektiven Primärrechtsschutz vor Zuschlag.",
        ),
        stationen=(
            "Vergabeart und Schwelle: Auftraggeber, Auftragsgegenstand, Schaetzung, Verfahrensart und Fristen klaeren.",
            "Vergabeunterlagen: Eignung, Zuschlagskriterien, Leistungsbeschreibung, Vertragsbedingungen und Nebenangebote pruefen.",
            "Rüge: erkennbaren Fehler, Kenntnisdatum, Frist und konkrete Abhilfe sauber formulieren.",
            "Nachpruefung: Antragsbefugnis, Rügepraeklusion, Zuschlagsverbot und Sachantrag vor Vergabekammer aufbauen.",
            "Arbeitsprodukt: Rügeschreiben, Nachpruefungsantrag, Auftraggebervermerk oder Wertungsmemo erstellen.",
        ),
        pruefraster=(
            "Ist der Auftraggeber und Auftragswert vergaberechtlich gebunden.",
            "Welcher Fehler ist wann erkennbar geworden.",
            "Ist die Rüge konkret, fristgerecht und auf Abhilfe gerichtet.",
            "Welche Wertungsentscheidung ist dokumentiert und nachpruefbar.",
            "Welcher Antrag vor Vergabekammer verhindert oder korrigiert den Zuschlag.",
        ),
        stop=(
            "Zuschlag droht vor Ablauf der Wartefrist.",
            "Rügefrist kann praekludieren.",
            "Vergabeunterlagen oder Dokumentation fehlen.",
        ),
    ),
    ThemenProfil(
        key="urheber",
        label="Urheber- und Medienrecht",
        rolle="Urheberrechtlicher Bearbeiter fuer Werk, Rechtekette, Lizenz, Nutzung, Schranken, Plattformen, Abmahnung und Unterlassung.",
        normen=(
            "UrhG Paragraf 2: geschuetzte Werke.",
            "UrhG Paragraf 15: Verwertungsrechte.",
            "UrhG Paragraf 31: Einraeumung von Nutzungsrechten.",
            "UrhG Paragraf 51: Zitatrecht.",
            "UrhG Paragraf 97: Unterlassung und Schadensersatz.",
            "KUG Paragraf 22 und Paragraf 23: Bildnisschutz und Ausnahmen.",
        ),
        entscheidungen=(
            "EuGH, Urteil vom 16.07.2009 - C-5/08: Infopaq verlangt eigene geistige Schoepfung als unionsrechtlichen Werkanker.",
            "EuGH, Urteil vom 13.02.2014 - C-466/12: Svensson grenzt Verlinkung und oeffentliche Wiedergabe ab.",
            "EuGH, Urteil vom 03.07.2012 - C-128/11: UsedSoft behandelt Erschoepfung bei Softwaredownloads.",
            "EuGH, Urteil vom 29.07.2019 - C-476/17: Pelham konkretisiert Sampling, Vervielfaeltigung und Kunstfreiheit.",
            "BGH, Urteil vom 12.11.2009 - I ZR 166/07: marions-kochbuch behandelt Lichtbildschutz und Online-Nutzung.",
        ),
        stationen=(
            "Schutzgegenstand: Werkart, Schoepfungshoehe, Lichtbild, Datenbank oder Leistungsschutzrecht bestimmen.",
            "Rechtekette: Urheber, Rechteinhaber, Lizenz, Gebiet, Dauer, Nutzungsart und Weitergabe pruefen.",
            "Nutzung: Vervielfaeltigung, oeffentliche Wiedergabe, Bearbeitung, Upload, Plattform und KI-Bezug trennen.",
            "Schranken: Zitat, Unterricht, Text und Data Mining, Privatkopie und Berichterstattung konkret anwenden.",
            "Arbeitsprodukt: Rechteclearing, Abmahnung, Lizenzklausel, Unterlassungserklaerung oder Verteidigungsmemo formulieren.",
        ),
        pruefraster=(
            "Welcher Schutzgegenstand ist betroffen.",
            "Wer hat welche Rechte in welcher Kette erworben.",
            "Welche konkrete Nutzung loest welches Verwertungsrecht aus.",
            "Welche Schranke greift mit welchen Voraussetzungen.",
            "Welche Rechtsfolge ist verhältnismaessig und beweisbar.",
        ),
        stop=(
            "Einstweilige Verfuegung oder Plattform-Takedown laeuft.",
            "Rechtekette ist unvollstaendig.",
            "Unterlassungserklaerung wird ohne Reichweitenpruefung verlangt.",
        ),
    ),
    ThemenProfil(
        key="it",
        label="IT-Recht",
        rolle="IT-rechtlicher Bearbeiter fuer Software, SaaS, IT-Projekte, Cloud, Leistungsstoerung, Datenschutzschnittstellen, Service-Level und Vertragsabnahme.",
        normen=(
            "BGB Paragraf 327: Verbrauchervertraege ueber digitale Produkte.",
            "BGB Paragraf 327e: Vertragsmaessigkeit digitaler Produkte.",
            "BGB Paragraf 433: Kaufrechtliche Grundpflichten bei Hardware und Standardsoftware.",
            "BGB Paragraf 631: Werkvertragliche Pflichten bei Projektleistungen.",
            "BGB Paragraf 634: Rechte bei Maengeln des Werkes.",
            "BGB Paragraf 280: Schadensersatz wegen Pflichtverletzung.",
        ),
        entscheidungen=(
            "EuGH, Urteil vom 03.07.2012 - C-128/11: UsedSoft behandelt Erschoepfung bei Softwaredownloads.",
            "BGH, Urteil vom 15.11.2006 - XII ZR 120/04: Application-Service-Providing kann mietvertragliche Elemente tragen.",
            "BGH, Urteil vom 04.03.2010 - III ZR 79/09: Internet-System-Vertrag ist regelmaessig werkvertraglich gepraegt.",
            "BGH, Urteil vom 24.01.2013 - VII ZR 37/12: IT-Projektvertraege verlangen klare Leistungsbeschreibung und Abnahmepruefung.",
            "BGH, Urteil vom 19.07.2012 - VII ZR 262/11: Werklohn setzt bei werkvertraglicher Praegung grundsaetzlich Abnahmefaehigkeit voraus.",
        ),
        stationen=(
            "Leistungsmodell: Kauf, Miete, Werk, Dienst, SaaS, Cloud oder Mischvertrag einordnen.",
            "Pflichtenheft: Funktion, Schnittstelle, Meilenstein, Testfall, Service-Level und Abnahme festlegen.",
            "Stoerung: Mangel, Verzug, Change Request, Mitwirkungsdefizit und Eskalationsmechanik trennen.",
            "Rechte und Daten: Nutzungsrechte, Open Source, Datenschutzschnittstelle, Zugriff und Loeschung pruefen.",
            "Arbeitsprodukt: IT-Vertragsklausel, Maengelruege, Abnahmeprotokoll, Exit-Plan oder Projektmemo erstellen.",
        ),
        pruefraster=(
            "Welche Vertragstypen praegen die Leistung.",
            "Welche Spezifikation ist messbar und abnahmefaehig.",
            "Welche Mitwirkung hat gefehlt oder war verzugsrelevant.",
            "Welche Nutzungsrechte und Datenpflichten sind erforderlich.",
            "Welche Eskalation verhindert Projektstillstand.",
        ),
        stop=(
            "Produktivsystem, Datenzugriff oder Sicherheitsvorfall ist akut betroffen.",
            "Abnahme oder Kuendigung soll ohne belastbare Maengelliste erfolgen.",
            "Open-Source- oder Datenschutzrisiko ist ungeklaert.",
        ),
    ),

    ThemenProfil(
        key="bauplanung",
        label="Bauleitplanung, Normenkontrolle und städtebauliche Verträge",
        rolle="Baurechtlicher Bearbeiter fuer Bauleitplanung, Normenkontrolle, Bebauungsplan-Festsetzungen, städtebauliche Verträge, Durchführungsverträge, Erschließung und Planerhaltung.",
        normen=(
            "BauGB Paragraf 1 Absatz 3: städtebauliche Erforderlichkeit der Planung.",
            "BauGB Paragraf 1 Absatz 7: Abwägungsgebot fuer Plan, Festsetzung und Vertragsfolgen.",
            "BauGB Paragraf 2 Absatz 3: Ermittlung und Bewertung des Abwägungsmaterials.",
            "BauGB Paragraf 9: textliche und zeichnerische Festsetzungen des Bebauungsplans.",
            "BauGB Paragraf 11: städtebaulicher Vertrag mit Kausalität, Angemessenheit und Schriftform.",
            "BauGB Paragraf 12: vorhabenbezogener Bebauungsplan und Durchführungsvertrag.",
            "BauGB Paragraf 13 und Paragraf 13a: vereinfachtes und beschleunigtes Verfahren, Innenentwicklung.",
            "BauGB Paragraf 124: Erschließungsvertrag als Spezialregelung.",
            "BauGB Paragraf 214 und Paragraf 215: Planerhaltung und Rügefrist.",
            "BauNVO Paragrafen 1 bis 23: Art und Maß der baulichen Nutzung, Bauweise und überbaubare Grundstücksflächen.",
        ),
        entscheidungen=(
            "BVerwG, Urteil vom 25.11.2005 - 4 C 15.04: Kostenübernahme in städtebaulichen Verträgen braucht zurechenbaren städtebaulichen Bezug und darf nicht nicht delegierbare Gemeindeaufgaben verlagern.",
            "BVerwG, Urteil vom 29.01.2009 - 4 C 15.07: Folgekostenverträge können bei mehreren Plangebieten tragfähig sein, wenn ein transparentes Gesamtkonzept die Kausalität belegt.",
            "BVerwG, Urteil vom 01.12.2010 - 9 C 8.09: Der Erschließungsvertrag nach BauGB Paragraf 124 ist gegenüber BauGB Paragraf 11 die speziellere Regelung.",
            "BVerwG, Urteil vom 25.01.2021 - 9 C 1.19: Der Durchführungsvertrag nach BauGB Paragraf 12 bezieht sich auf die Einzelerschließung und Durchführung eines Vorhabens.",
            "BVerwG, Urteil vom 25.06.2014 - 4 CN 4.13: Eine Festsetzung braucht eine passende Rechtsgrundlage im BauGB-Festsetzungskatalog oder in zugelassenem Landesrecht.",
            "BVerwG, Beschluss vom 20.06.2017 - 4 BN 30.16: BauGB Paragraf 13a setzt eine echte Maßnahme der Innenentwicklung voraus.",
            "BVerwG, Urteil vom 25.06.2020 - 4 CN 5.18: Das beschleunigte Verfahren verlangt eine eigenständige Prüfung der Innenentwicklungsqualität.",
        ),
        stationen=(
            "Planangriff und Verfahrensstand: Satzungsbeschluss, Bekanntmachung, Rügefrist, Antragsteller und Rechtsschutzbedürfnis feststellen.",
            "Festsetzungen: BauGB Paragraf 9, BauNVO, Planzeichnung, textliche Festsetzungen, Bestimmtheit und Rechtsgrundlage prüfen.",
            "Städtebauliche Verträge: BauGB Paragraf 11, Folgekosten, Angemessenheit, Kausalität, Schriftform und Rückabwicklung prüfen.",
            "Vorhabenbezogener Plan: BauGB Paragraf 12, Vorhaben- und Erschließungsplan, Durchführungsvertrag, Frist und Kosten abgleichen.",
            "Erschließung und Kosten: BauGB Paragraf 124, Erschließungsbeiträge, Dritter, Anlagenliste und Umgehungsrisiko ordnen.",
            "Innenentwicklung und Verfahren: BauGB Paragraf 13, 13a und Übergangsfragen zu 13b, Umweltprüfung und Beteiligung kontrollieren.",
            "Abwägung und Planerhaltung: BauGB Paragraf 1 Absatz 7, Paragrafen 214 und 215, Fehlergewicht und ergänzendes Verfahren darstellen.",
            "Arbeitsprodukt: Normenkontrollantrag, Verteidigungsschriftsatz, Heilungsvermerk, Vertragsprüfung oder Festsetzungssynopse erstellen.",
        ),
        pruefraster=(
            "Welche Satzung, Festsetzung oder Vertragsklausel ist genau angegriffen.",
            "Welche Rechtsgrundlage trägt die Festsetzung oder Vertragsleistung.",
            "Ist die Festsetzung bestimmt, erforderlich und abgewogen.",
            "Ist die Vertragsleistung kausal, angemessen, schriftlich und nicht kopplungswidrig.",
            "Greifen Planerhaltungsregeln oder ist der Fehler beachtlich.",
            "Welcher Rechtsschutzweg passt: Normenkontrolle, Leistungsklage, Feststellung oder Planheilung.",
        ),
        stop=(
            "Rügefrist nach BauGB Paragraf 215 oder Antragsfrist nach VwGO Paragraf 47 ist unklar.",
            "Vertrag und Bebauungsplan widersprechen einander in Nutzung, Kosten, Frist oder Erschließung.",
            "Festsetzung hat keine erkennbare Rechtsgrundlage oder ist im Vollzug unbestimmt.",
            "Folgekosten oder Erschließungskosten werden ohne nachvollziehbare Kausalitätskette verlangt.",
        ),
        skelette=(
            "Normenkontrollbaustein: Die Festsetzung [Bezeichnung] ist unwirksam, weil BauGB Paragraf 9 keine tragfähige Rechtsgrundlage für [Regelungsinhalt] eröffnet und der Fehler beachtlich bleibt.",
            "Vertragsbaustein: Die Kostenübernahme ist nur tragfähig, wenn [Maßnahme] als Voraussetzung oder Folge des Vorhabens [Projekt] nachvollziehbar, transparent und angemessen zurechenbar ist.",
            "Heilungsvermerk: Der Fehler kann nur über ein ergänzendes Verfahren repariert werden, wenn die Gemeinde das fehlende Abwägungsmaterial ermittelt, bewertet und erneut beschließt.",
        ),
    ),
    ThemenProfil(
        key="bau",
        label="Bau- und Architektenrecht",
        rolle="Baurechtlicher Bearbeiter fuer Bauvertrag, Architektenleistung, Maengel, Nachtrag, Abnahme, Bauzeit, Sicherheiten und Bauprozess.",
        normen=(
            "BGB Paragraf 631: Werkvertragliche Hauptpflichten.",
            "BGB Paragraf 633: Sach- und Rechtsmaengel des Werkes.",
            "BGB Paragraf 634: Rechte des Bestellers bei Maengeln.",
            "BGB Paragraf 640: Abnahme.",
            "BGB Paragraf 650a: Bauvertrag.",
            "BGB Paragraf 650q: Architekten- und Ingenieurvertrag.",
            "BauGB Paragraf 9: Festsetzungen des Bebauungsplans als Rahmen fuer Genehmigungs- und Planungsrisiken.",
            "BauGB Paragraf 11 und Paragraf 12: städtebaulicher Vertrag, Durchführungsvertrag und vorhabenbezogener Bebauungsplan.",
            "BauGB Paragraf 124: Erschließungsvertrag als Spezialregelung.",
            "BauNVO Paragrafen 1 bis 23: Art und Maß der Nutzung, Bauweise und überbaubare Grundstücksflächen.",
        ),
        entscheidungen=(
            "BGH, Urteil vom 22.02.2018 - VII ZR 46/17: fiktive Maengelbeseitigungskosten sind im Werkvertragsrecht nicht mehr als Schaden abrechenbar.",
            "BGH, Urteil vom 08.11.2007 - VII ZR 183/05: Architekt und Unternehmer koennen bei Baumangel und Ueberwachungsfehler gesamtschuldnerisch haften.",
            "BGH, Urteil vom 24.01.2008 - VII ZR 280/05: Bedenkenhinweis muss rechtzeitig, inhaltlich klar und adressatengerecht erfolgen.",
            "BGH, Urteil vom 10.10.2013 - VII ZR 19/12: Abnahme und Abnahmereife steuern Faelligkeit und Maengelrechte.",
            "BGH, Urteil vom 25.06.2015 - VII ZR 220/14: Nachtraege verlangen nachvollziehbare Grundlage und Abgrenzung vom Vertragssoll.",
            "BVerwG, Urteil vom 29.01.2009 - 4 C 15.07: Folgekostenverträge können bei mehreren Plangebieten tragfähig sein, wenn ein transparentes Gesamtkonzept die Kausalität belegt.",
            "BVerwG, Urteil vom 25.06.2014 - 4 CN 4.13: Bebauungsplan-Festsetzungen brauchen eine passende Rechtsgrundlage im Festsetzungskatalog.",
            "BVerwG, Urteil vom 01.12.2010 - 9 C 8.09: Der Erschließungsvertrag nach BauGB Paragraf 124 ist gegenüber BauGB Paragraf 11 die speziellere Regelung.",
        ),
        stationen=(
            "Vertragssoll: Leistungsbeschreibung, Plaene, Nachtraege, Termine, Verguetung und Sicherheiten erfassen.",
            "Bauablauf: Behinderung, Bedenkenhinweis, Koordination, Abnahme und Dokumentation ordnen.",
            "Mangel: Soll-Ist-Abweichung, Verantwortlichkeit, Fristsetzung, Selbstvornahme und Schaden pruefen.",
            "Architekt: Leistungsphase, Ueberwachungspflicht, Kostenkontrolle, Haftungsanteil und Gesamtschuld darstellen.",
            "Städtebauliche Verträge: Folgekosten, Erschließung, Durchführungsvertrag, Kausalität und Angemessenheit prüfen.",
            "Festsetzungen: Bebauungsplan, BauNVO-Werte, Baufenster, örtliche Bauvorschriften und Befreiungsbedarf in die Planungspflichten übersetzen.",
            "Arbeitsprodukt: Maengelruege, Nachtragsbewertung, Abnahmeprotokoll, Klageentwurf, Vertragsprüfung oder Gutachterfragen formulieren.",
        ),
        pruefraster=(
            "Welches Vertragssoll ist beweisbar vereinbart.",
            "Ist abgenommen oder abnahmereif.",
            "Welche Maengelrechte sind nach Fristsetzung eroeffnet.",
            "Welche Bauzeit- oder Nachtragsfolge ist kausal belegt.",
            "Welche technische Frage muss ein Sachverstaendiger klaeren.",
            "Welche Festsetzung oder städtebauliche Vertragsbindung begrenzt Planung, Genehmigung oder Kostenweitergabe.",
        ),
        stop=(
            "Abnahme, Kuendigung oder Sicherheitenabruf steht unmittelbar bevor.",
            "Beweissicherung ist vor Nachbesserung noetig.",
            "Technische Ursache oder Verantwortlichkeit ist ungeklärt.",
            "Bebauungsplan, Durchführungsvertrag oder Folgekostenlast wurde im Projektvertrag nicht transparent übernommen.",
        ),
    ),
    ThemenProfil(
        key="default",
        label="Deutsches Recht",
        rolle="Juristischer Bearbeiter fuer deutsche Rechtsfragen mit Fokus auf Sachverhaltsordnung, Normpruefung, Beweislast, Fristen und verwertbare Schriftprodukte.",
        normen=(
            "BGB Paragraf 242: Treu und Glauben als Korrektiv privatrechtlicher Rechtsausuebung.",
            "BGB Paragraf 280: Pflichtverletzung als Kern des vertraglichen Schadensersatzes.",
            "BGB Paragraf 823: deliktische Haftung bei Rechtsgutsverletzung.",
            "ZPO Paragraf 138: Erklaerungslast und Wahrheitspflicht im Zivilprozess.",
            "ZPO Paragraf 286: freie Beweiswuerdigung.",
            "ZPO Paragraf 253: Mindestinhalt der Klageschrift.",
        ),
        entscheidungen=(
            "BVerfG, Urteil vom 15.01.1958 - 1 BvR 400/51: Grundrechte wirken als objektive Wertordnung in die gesamte Rechtsordnung.",
            "BGH, Urteil vom 05.10.1961 - VII ZR 207/60: cic-Grundsaetze praegen vorvertragliche Pflichten.",
            "BGH, Urteil vom 19.01.1999 - VI ZR 53/98: haftungsrechtliche Zurechnung verlangt Pflichtverletzung, Schaden und Kausalitaet.",
            "BGH, Urteil vom 12.03.2004 - V ZR 257/03: Auslegung und Treu-und-Glauben-Korrektur haengen am konkreten Einzelfall.",
            "BGH, Urteil vom 18.01.2017 - VIII ZR 17/16: Substantiierung verlangt Vortrag der anspruchsbegruendenden Tatsachen.",
        ),
        stationen=(
            "Sachverhalt ordnen: Beteiligte, Dokumente, Zeitachse, Fristen, Belege und Ziel erfassen.",
            "Rechtsgebiet bestimmen: Anspruch, Einwendung, Verfahren und Zuständigkeit trennen.",
            "Normpruefung aufbauen: Tatbestandsmerkmale, Rechtsfolge, Beweislast und Gegenrechte ausarbeiten.",
            "Streitstoff verdichten: unstreitig, streitig, beweisbeduerftig, entscheidungserheblich unterscheiden.",
            "Arbeitsprodukt erstellen: Memo, Tabelle, Schriftsatz, Vertrag, Klausel, Pruefvermerk oder Entscheidungsvorschlag.",
        ),
        pruefraster=(
            "Wer will was von wem woraus.",
            "Welche Frist, Form oder Zuständigkeit kann das Ergebnis kippen.",
            "Welche Tatsachen sind unstreitig und welche muessen bewiesen werden.",
            "Welche Norm traegt Anspruch, Einwendung oder Rechtsfolge.",
            "Welcher naechste Output loest das konkrete Problem.",
        ),
        stop=(
            "Frist oder Form kann nicht sicher bestimmt werden.",
            "Tatsachen sind fuer eine tragende Subsumtion unzureichend.",
            "Strafrechtliche, insolvenzrechtliche oder berufsrechtliche Nebenrisiken sind erkennbar.",
        ),
    ),
)


KEYWORDS: tuple[tuple[str, str], ...] = (
    ("normenkontrolle-bauleitplanung", "bauplanung"),
    ("bauleit", "bauplanung"),
    ("bebauungsplan", "bauplanung"),
    ("bauplanung", "bauplanung"),
    ("staedtebau", "bauplanung"),
    ("festsetzung", "bauplanung"),
    ("arbeits", "arbeits"),
    ("kuendig", "arbeits"),
    ("befrist", "arbeits"),
    ("zeugnis", "arbeits"),
    ("miet", "miet"),
    ("wohnung", "miet"),
    ("weg", "miet"),
    ("famil", "famil"),
    ("unterhalt", "famil"),
    ("scheidung", "famil"),
    ("straf", "straf"),
    ("owi", "straf"),
    ("amtsanwaltschaft", "straf"),
    ("staatsanwaltschaft", "straf"),
    ("datenschutz", "datenschutz"),
    ("dsgvo", "datenschutz"),
    ("insolvenz", "insolvenz"),
    ("sanierung", "insolvenz"),
    ("starug", "insolvenz"),
    ("steuer", "steuer"),
    ("finanzgericht", "steuer"),
    ("gesellschaft", "gesellschaft"),
    ("corporate", "gesellschaft"),
    ("register", "gesellschaft"),
    ("verfass", "verfass"),
    ("grundrecht", "verfass"),
    ("versicher", "versicherung"),
    ("liquiditaet", "liquiditaet"),
    ("liquiditaets", "liquiditaet"),
    ("sozial", "sozial"),
    ("verwaltungs", "verwaltung"),
    ("verwaltung", "verwaltung"),
    ("vergab", "vergabe"),
    ("urheber", "urheber"),
    ("medien", "urheber"),
    ("it-recht", "it"),
    ("software", "it"),
    ("cloud", "it"),
    ("bau", "bau"),
    ("architekt", "bau"),
)


PROFILE_BY_KEY = {p.key: p for p in PROFILE}


def profile_for(slug: str, text: str = "") -> ThemenProfil:
    slug_hay = slug.lower()
    for needle, key in KEYWORDS:
        if needle in slug_hay:
            return PROFILE_BY_KEY[key]
    return PROFILE_BY_KEY["default"]
